import {
	AppWindow,
	Banknote,
	BookOpen,
	Bot,
	ChevronDown,
	ChevronRight,
	CircleHelp,
	Clipboard,
	ClipboardPaste,
	Clock,
	CopyPlus,
	DraftingCompass,
	Eye,
	Flower2,
	Gem,
	Gift,
	Globe,
	Hash,
	Heart,
	HeartCrack,
	HeartPulse,
	Image,
	Laptop,
	Leaf,
	Library,
	Link,
	Lock,
	LockOpen,
	Mail,
	MessageCircle,
	Moon,
	Music,
	Package,
	Palette,
	Pencil,
	PictureInPicture2,
	Pin,
	Plus,
	Puzzle,
	Rainbow,
	Rocket,
	Save,
	Scissors,
	Search,
	Settings,
	Shell,
	Smartphone,
	Sparkles,
	Sprout,
	SquareCheckBig,
	SquareDashed,
	Star,
	Sun,
	SunMoon,
	ThumbsDown,
	ThumbsUp,
	Trash2,
	TreePine,
	TriangleAlert,
	User,
	Users,
	Video,
	Wand,
	WandSparkles,
	X
} from 'lucide-react';
import type { ComponentType } from 'react';

// 1:1 Lucide twins for every emoji icon the app uses, each with a colour
// (theme vars where a semantic fits, rainbow stops for flavour). The shared
// Icon component consults this map when the theme's icon style is 'lucide' —
// unmapped glyphs simply stay emoji, so the map can grow lazily.

export type TtLucideMapping = {
	Icon: ComponentType<{ size?: number | string; color?: string; strokeWidth?: number | string }>;
	color: string;
};

export const LUCIDE_FOR_EMOJI: Record<string, TtLucideMapping> = {
	'🎨': { Icon: Palette, color: 'var(--tt-accent, hotpink)' },
	'👀': { Icon: Eye, color: 'var(--tt-ink, #16161a)' },
	'▸': { Icon: ChevronRight, color: 'var(--tt-muted, #9a9aa6)' },
	'▾': { Icon: ChevronDown, color: 'var(--tt-muted, #9a9aa6)' },
	'🍂': { Icon: Leaf, color: '#d97706' },
	'🌳': { Icon: TreePine, color: 'var(--tt-positive, #2f8f4f)' },
	'🌀': { Icon: Shell, color: 'var(--tt-rainbow-4, #47b5e6)' },
	'🌱': { Icon: Sprout, color: 'var(--tt-positive, #2f8f4f)' },
	'✏️': { Icon: Pencil, color: 'var(--tt-warning, #ffbc48)' },
	'🐑': { Icon: CopyPlus, color: 'var(--tt-muted, #9a9aa6)' },
	'📋': { Icon: Clipboard, color: 'var(--tt-text, #5a5a66)' },
	'✂️': { Icon: Scissors, color: '#d97706' },
	'📥': { Icon: ClipboardPaste, color: 'var(--tt-positive, #2f8f4f)' },
	'🔗': { Icon: Link, color: 'var(--tt-link, #2f8fd6)' },
	'🔒': { Icon: Lock, color: 'var(--tt-muted, #9a9aa6)' },
	'🔓': { Icon: LockOpen, color: 'var(--tt-muted, #9a9aa6)' },
	'👥': { Icon: Users, color: 'var(--tt-link, #2f8fd6)' },
	'🌍': { Icon: Globe, color: 'var(--tt-positive, #2f8f4f)' },
	'✉️': { Icon: Mail, color: 'var(--tt-link, #2f8fd6)' },
	'🗑️': { Icon: Trash2, color: 'var(--tt-danger, #d6455a)' },
	'📌': { Icon: Pin, color: 'var(--tt-warning, #ffbc48)' },
	'❌': { Icon: X, color: 'var(--tt-danger, #d6455a)' },
	'🧙‍♂️': { Icon: WandSparkles, color: 'var(--tt-rainbow-5, #a555e8)' },
	'🪄': { Icon: Wand, color: 'var(--tt-rainbow-5, #a555e8)' },
	'📦': { Icon: Package, color: '#d97706' },
	'📚': { Icon: Library, color: 'var(--tt-rainbow-4, #47b5e6)' },
	'💬': { Icon: MessageCircle, color: 'var(--tt-positive, #2f8f4f)' },
	'💯': { Icon: Hash, color: 'var(--tt-rainbow-4, #47b5e6)' },
	'🌗': { Icon: SunMoon, color: 'var(--tt-rainbow-5, #a555e8)' },
	'📐': { Icon: DraftingCompass, color: 'var(--tt-muted, #9a9aa6)' },
	'🌺': { Icon: Flower2, color: 'var(--tt-accent, hotpink)' },
	'📖': { Icon: BookOpen, color: 'var(--tt-link, #2f8fd6)' },
	'✅': { Icon: SquareCheckBig, color: 'var(--tt-positive, #2f8f4f)' },
	'👤': { Icon: User, color: 'var(--tt-muted, #9a9aa6)' },
	'🌟': { Icon: Star, color: 'var(--tt-warning, #ffbc48)' },
	'⭐': { Icon: Star, color: 'var(--tt-warning, #ffbc48)' },
	'✨': { Icon: Sparkles, color: 'var(--tt-warning, #ffbc48)' },
	'🎁': { Icon: Gift, color: 'var(--tt-accent, hotpink)' },
	'⚙️': { Icon: Settings, color: 'var(--tt-muted, #9a9aa6)' },
	'🔮': { Icon: Gem, color: 'var(--tt-rainbow-5, #a555e8)' },
	'💻': { Icon: Laptop, color: 'var(--tt-muted, #9a9aa6)' },
	'📱': { Icon: Smartphone, color: 'var(--tt-muted, #9a9aa6)' },
	'➕': { Icon: Plus, color: 'var(--tt-positive, #2f8f4f)' },
	'⚠️': { Icon: TriangleAlert, color: 'var(--tt-warning, #ffbc48)' },
	'❓': { Icon: CircleHelp, color: 'var(--tt-muted, #9a9aa6)' },
	'🔍': { Icon: Search, color: 'var(--tt-muted, #9a9aa6)' },
	'🌈': { Icon: Rainbow, color: 'var(--tt-accent, hotpink)' },
	'🚀': { Icon: Rocket, color: 'var(--tt-rainbow-4, #47b5e6)' },
	'🤖': { Icon: Bot, color: 'var(--tt-muted, #9a9aa6)' },
	'💵': { Icon: Banknote, color: 'var(--tt-positive, #2f8f4f)' },
	'💰': { Icon: Banknote, color: 'var(--tt-positive, #2f8f4f)' },
	'🧩': { Icon: Puzzle, color: 'var(--tt-rainbow-4, #47b5e6)' },
	'❤️': { Icon: Heart, color: 'var(--tt-danger, #d6455a)' },
	'💔': { Icon: HeartCrack, color: 'var(--tt-danger, #d6455a)' },
	'💗': { Icon: HeartPulse, color: 'var(--tt-accent, hotpink)' },
	'⏰': { Icon: Clock, color: 'var(--tt-muted, #9a9aa6)' },
	'👍': { Icon: ThumbsUp, color: 'var(--tt-positive, #2f8f4f)' },
	'👎': { Icon: ThumbsDown, color: 'var(--tt-danger, #d6455a)' },
	'☀️': { Icon: Sun, color: 'var(--tt-warning, #ffbc48)' },
	'🌙': { Icon: Moon, color: 'var(--tt-rainbow-5, #a555e8)' },
	'🖼️': { Icon: Image, color: 'var(--tt-rainbow-4, #47b5e6)' },
	'🎥': { Icon: Video, color: 'var(--tt-rainbow-4, #47b5e6)' },
	'🎵': { Icon: Music, color: 'var(--tt-rainbow-5, #a555e8)' },
	'🎈': { Icon: PictureInPicture2, color: 'var(--tt-accent, hotpink)' },
	'🪟': { Icon: AppWindow, color: 'var(--tt-muted, #9a9aa6)' },
	'▢': { Icon: SquareDashed, color: 'var(--tt-muted, #9a9aa6)' },
	'💾': { Icon: Save, color: 'var(--tt-link, #2f8fd6)' }
};
