import {
	AppWindow,
	Banknote,
	BookOpen,
	Bookmark,
	Bot,
	Box,
	Brackets,
	Check,
	ChefHat,
	ChevronDown,
	ChevronRight,
	ChevronsDownUp,
	ChevronsUpDown,
	CircleHelp,
	Clipboard,
	ClipboardPaste,
	Clock,
	Contact,
	CopyPlus,
	Copy,
	DraftingCompass,
	Eye,
	Flower2,
	Gem,
	Gift,
	Globe,
	Hash,
	Heart,
	HeartCrack,
	HeartPulse,
	Image,
	Laptop,
	LayoutTemplate,
	Leaf,
	Library,
	Link,
	ListChecks,
	Lock,
	LockOpen,
	Mail,
	MessageCircle,
	Monitor,
	Moon,
	Music,
	NotebookPen,
	NotebookText,
	Package,
	PackageOpen,
	Paintbrush,
	Palette,
	Pencil,
	PenLine,
	PictureInPicture2,
	Pin,
	PinOff,
	Plus,
	Puzzle,
	Quote,
	Rainbow,
	Replace,
	Rocket,
	Save,
	Scissors,
	Search,
	Settings,
	Share2,
	Shell,
	Smartphone,
	Sparkles,
	Sprout,
	SquareCheckBig,
	SquareDashed,
	SquareFunction,
	Star,
	Sun,
	SunMoon,
	TextCursorInput,
	ThumbsDown,
	ThumbsUp,
	ToggleLeft,
	Trash2,
	TreePine,
	TriangleAlert,
	User,
	Users,
	Video,
	Wand,
	WandSparkles,
	X
} from 'lucide-react';
import type { ComponentType } from 'react';

// The Lucide icon language — the professional sibling of the emoji icons.
//
// LUCIDE_ICONS is the curated palette: kebab names → coloured Lucide
// components (semantic theme vars where one fits, rainbow stops for flavour).
// Menu actions pick CONTEXTUAL icons by name via their `lucide` field
// (collapse-all → chevrons folding, not a literal leaf); anything without an
// explicit name falls back through LUCIDE_FOR_EMOJI, and unmapped glyphs stay
// emoji — so the system degrades gracefully and grows lazily.

export type TtLucideIconDef = {
	Icon: ComponentType<{ size?: number | string; color?: string; strokeWidth?: number | string }>;
	color: string;
};

const ACCENT = 'var(--tt-accent, hotpink)';
const INK = 'var(--tt-ink, #16161a)';
const TEXT = 'var(--tt-text, #5a5a66)';
const MUTED = 'var(--tt-muted, #9a9aa6)';
const LINKC = 'var(--tt-link, #2f8fd6)';
const POSITIVE = 'var(--tt-positive, #2f8f4f)';
const DANGER = 'var(--tt-danger, #d6455a)';
const WARNING = 'var(--tt-warning, #ffbc48)';
const BLUE = 'var(--tt-rainbow-4, #47b5e6)';
const PURPLE = 'var(--tt-rainbow-5, #a555e8)';
const AMBER = '#d97706';

export const LUCIDE_ICONS: Record<string, TtLucideIconDef> = {
	'app-window': { Icon: AppWindow, color: MUTED },
	banknote: { Icon: Banknote, color: POSITIVE },
	'book-open': { Icon: BookOpen, color: LINKC },
	bookmark: { Icon: Bookmark, color: LINKC },
	bot: { Icon: Bot, color: MUTED },
	box: { Icon: Box, color: AMBER },
	brackets: { Icon: Brackets, color: BLUE },
	check: { Icon: Check, color: POSITIVE },
	'chef-hat': { Icon: ChefHat, color: ACCENT },
	'chevron-down': { Icon: ChevronDown, color: MUTED },
	'chevron-right': { Icon: ChevronRight, color: MUTED },
	'chevrons-down-up': { Icon: ChevronsDownUp, color: MUTED },
	'chevrons-up-down': { Icon: ChevronsUpDown, color: MUTED },
	'circle-help': { Icon: CircleHelp, color: MUTED },
	clipboard: { Icon: Clipboard, color: TEXT },
	'clipboard-paste': { Icon: ClipboardPaste, color: POSITIVE },
	clock: { Icon: Clock, color: MUTED },
	contact: { Icon: Contact, color: MUTED },
	copy: { Icon: Copy, color: TEXT },
	'copy-plus': { Icon: CopyPlus, color: MUTED },
	'drafting-compass': { Icon: DraftingCompass, color: MUTED },
	eye: { Icon: Eye, color: INK },
	'flower-2': { Icon: Flower2, color: ACCENT },
	gem: { Icon: Gem, color: PURPLE },
	gift: { Icon: Gift, color: ACCENT },
	globe: { Icon: Globe, color: POSITIVE },
	hash: { Icon: Hash, color: BLUE },
	heart: { Icon: Heart, color: DANGER },
	'heart-crack': { Icon: HeartCrack, color: DANGER },
	'heart-pulse': { Icon: HeartPulse, color: ACCENT },
	image: { Icon: Image, color: BLUE },
	laptop: { Icon: Laptop, color: MUTED },
	'layout-template': { Icon: LayoutTemplate, color: MUTED },
	leaf: { Icon: Leaf, color: AMBER },
	library: { Icon: Library, color: BLUE },
	link: { Icon: Link, color: LINKC },
	'list-checks': { Icon: ListChecks, color: POSITIVE },
	lock: { Icon: Lock, color: MUTED },
	'lock-open': { Icon: LockOpen, color: MUTED },
	mail: { Icon: Mail, color: LINKC },
	'message-circle': { Icon: MessageCircle, color: POSITIVE },
	monitor: { Icon: Monitor, color: MUTED },
	moon: { Icon: Moon, color: PURPLE },
	music: { Icon: Music, color: PURPLE },
	'notebook-pen': { Icon: NotebookPen, color: LINKC },
	'notebook-text': { Icon: NotebookText, color: PURPLE },
	package: { Icon: Package, color: AMBER },
	'package-open': { Icon: PackageOpen, color: AMBER },
	paintbrush: { Icon: Paintbrush, color: ACCENT },
	palette: { Icon: Palette, color: ACCENT },
	'pen-line': { Icon: PenLine, color: WARNING },
	pencil: { Icon: Pencil, color: WARNING },
	'picture-in-picture-2': { Icon: PictureInPicture2, color: ACCENT },
	pin: { Icon: Pin, color: WARNING },
	'pin-off': { Icon: PinOff, color: MUTED },
	plus: { Icon: Plus, color: POSITIVE },
	puzzle: { Icon: Puzzle, color: BLUE },
	quote: { Icon: Quote, color: POSITIVE },
	rainbow: { Icon: Rainbow, color: ACCENT },
	replace: { Icon: Replace, color: BLUE },
	rocket: { Icon: Rocket, color: BLUE },
	save: { Icon: Save, color: LINKC },
	scissors: { Icon: Scissors, color: AMBER },
	search: { Icon: Search, color: MUTED },
	settings: { Icon: Settings, color: MUTED },
	'share-2': { Icon: Share2, color: LINKC },
	shell: { Icon: Shell, color: BLUE },
	smartphone: { Icon: Smartphone, color: MUTED },
	sparkles: { Icon: Sparkles, color: WARNING },
	sprout: { Icon: Sprout, color: POSITIVE },
	'square-check-big': { Icon: SquareCheckBig, color: POSITIVE },
	'square-dashed': { Icon: SquareDashed, color: MUTED },
	'square-function': { Icon: SquareFunction, color: MUTED },
	star: { Icon: Star, color: WARNING },
	sun: { Icon: Sun, color: WARNING },
	'sun-moon': { Icon: SunMoon, color: PURPLE },
	'text-cursor-input': { Icon: TextCursorInput, color: WARNING },
	'thumbs-down': { Icon: ThumbsDown, color: DANGER },
	'thumbs-up': { Icon: ThumbsUp, color: POSITIVE },
	'toggle-left': { Icon: ToggleLeft, color: PURPLE },
	'trash-2': { Icon: Trash2, color: DANGER },
	'tree-pine': { Icon: TreePine, color: POSITIVE },
	'triangle-alert': { Icon: TriangleAlert, color: WARNING },
	user: { Icon: User, color: MUTED },
	users: { Icon: Users, color: LINKC },
	video: { Icon: Video, color: BLUE },
	wand: { Icon: Wand, color: PURPLE },
	'wand-sparkles': { Icon: WandSparkles, color: PURPLE },
	x: { Icon: X, color: DANGER }
};

/** Fallback for icons that only exist as emoji strings (no explicit name). */
export const LUCIDE_FOR_EMOJI: Record<string, string> = {
	'🎨': 'palette',
	'👀': 'eye',
	'▸': 'chevron-right',
	'▾': 'chevron-down',
	'🍂': 'chevrons-down-up',
	'🌳': 'tree-pine',
	'🌀': 'shell',
	'🌱': 'sprout',
	'✏️': 'pencil',
	'🐑': 'copy-plus',
	'📋': 'clipboard',
	'✂️': 'scissors',
	'📥': 'clipboard-paste',
	'🔗': 'link',
	'🔒': 'lock',
	'🔓': 'lock-open',
	'👥': 'users',
	'🌍': 'globe',
	'✉️': 'mail',
	'🗑️': 'trash-2',
	'📌': 'pin',
	'❌': 'x',
	'🧙‍♂️': 'wand-sparkles',
	'🪄': 'wand',
	'📦': 'package',
	'📚': 'library',
	'💬': 'message-circle',
	'💯': 'hash',
	'🌗': 'toggle-left',
	'📐': 'drafting-compass',
	'🌺': 'flower-2',
	'📖': 'book-open',
	'✅': 'square-check-big',
	'👤': 'user',
	'🌟': 'star',
	'⭐': 'star',
	'✨': 'sparkles',
	'🎁': 'gift',
	'⚙️': 'settings',
	'🔮': 'gem',
	'💻': 'laptop',
	'📱': 'smartphone',
	'➕': 'plus',
	'⚠️': 'triangle-alert',
	'❓': 'circle-help',
	'🔍': 'search',
	'🌈': 'rainbow',
	'🚀': 'rocket',
	'🤖': 'bot',
	'💵': 'banknote',
	'💰': 'banknote',
	'🧩': 'puzzle',
	'❤️': 'heart',
	'💔': 'heart-crack',
	'💗': 'heart-pulse',
	'⏰': 'clock',
	'👍': 'thumbs-up',
	'👎': 'thumbs-down',
	'☀️': 'sun',
	'🌙': 'moon',
	'🖼️': 'image',
	'🎥': 'video',
	'🎵': 'music',
	'🎈': 'picture-in-picture-2',
	'🪟': 'app-window',
	'▢': 'square-dashed',
	'💾': 'save'
};
