import { byKey } from './lookup';
import type { Feature } from './types';

// The curated feature inventory the marketing engine fans out from. Every
// entry describes something that exists in the app today (route + code), in
// plain benefit language. Keep entries factual — the generators multiply
// whatever is written here across ~1000 pages.

export const FEATURES: Feature[] = [
	// ---------------------------------------------------------------- core
	{
		key: 'things-tree',
		name: 'The Things tree',
		emoji: '🌳',
		route: '/things',
		tagline: 'Every piece of your data, browsable as one tree.',
		description:
			'Thingtime turns anything you store into a navigable tree of things: nested keys, arrays and values with carets, count pills and rainbow depth guides.',
		category: 'core',
		audiences: ['power-users', 'developers', 'hobbyists', 'researchers'],
		highlights: ['Expand any branch with carets and count pills', 'Rainbow depth guides keep deep trees readable', 'Reader and developer views of the same data'],
		screen: 'things',
		answers: ['notion', 'obsidian', 'airtable']
	},
	{
		key: 'everything-is-a-thing',
		name: 'Everything is a thing',
		emoji: '📦',
		route: '/things',
		tagline: 'One model for posts, pages, schemas, apps and notes.',
		description:
			'Users, posts, comments, themes, webpages, schemas and app data all live as things with a kind, so one API, one permission model and one UI cover all of it.',
		category: 'core',
		audiences: ['developers', 'power-users', 'founders'],
		highlights: ['One collection, one permission model', 'Kinds describe shape, not silos', 'Child data stays relational, never buried in blobs'],
		screen: 'things',
		answers: ['notion', 'firebase', 'supabase']
	},
	{
		key: 'view-edit-editor-modes',
		name: 'View, Edit and Editor modes',
		emoji: '🎛️',
		route: '/things',
		tagline: 'Read it, tweak it, or open the raw editor.',
		description:
			'Switch between a reader view with headings and Yes/No booleans, an inline edit mode with dashed underlines, and a developer editor for the raw structure.',
		category: 'core',
		audiences: ['power-users', 'developers', 'students'],
		highlights: ['Reader view renders keys as headings', 'Inline edits with dashed-underline inputs', 'Developer editor for the raw shape'],
		screen: 'things'
	},
	{
		key: 'thing-permalinks',
		name: 'Permalinks for everything',
		emoji: '🔗',
		route: '/things',
		tagline: 'Every thing, post, comment and file has its own URL.',
		description:
			'Posts and comments get /post/:id, files get /media/:id and any thing gets /thing/:id, so anything in Thingtime can be linked, shared and embedded.',
		category: 'core',
		audiences: ['creators', 'teams', 'developers'],
		highlights: ['Timestamps link to permalinks', 'Files are things with their own page', 'Deep links open exactly the right thing'],
		screen: 'feed'
	},
	{
		key: 'search',
		name: 'Search',
		emoji: '🔍',
		route: '/search',
		tagline: 'Find any thing, person or post in one box.',
		description: 'Global search across things, posts and people, with emoji-aware matching and results that deep-link into the tree.',
		category: 'core',
		audiences: ['power-users', 'teams', 'students', 'researchers'],
		highlights: ['Search things, people and posts together', 'Emoji search actually works', 'Results deep-link into the exact branch'],
		screen: 'search'
	},
	{
		key: 'folders',
		name: 'Folders',
		emoji: '📁',
		route: '/things',
		tagline: 'Drive-style folders for your things.',
		description: 'The unified Things browser groups things into folders with sort, group, drag-and-drop and a right-click context menu.',
		category: 'data',
		audiences: ['teams', 'families', 'power-users', 'small-business'],
		highlights: ['Drag things into folders', 'Sort and group by kind, date or name', 'Right-click for the full context menu'],
		screen: 'things',
		answers: ['google-drive', 'notion']
	},
	{
		key: 'bulk-actions',
		name: 'Bulk move, copy, share and delete',
		emoji: '🧺',
		route: '/things',
		tagline: 'Select many things and act on all of them at once.',
		description: 'Multi-select in the Things browser and move, copy, share or delete in one request, including recursive folder copies.',
		category: 'data',
		audiences: ['teams', 'power-users', 'small-business'],
		highlights: ['Multi-select with shift and drag', 'Recursive folder copy and share', 'One request, one undo story'],
		screen: 'things'
	},
	{
		key: 'acl-sharing',
		name: 'Sharing and permissions',
		emoji: '🔐',
		route: '/things',
		tagline: 'Private by default, shared on your terms.',
		description:
			'Every thing carries an access list. Share with a person, a group, an app or the public, and let children inherit from their parent chain.',
		category: 'data',
		audiences: ['teams', 'families', 'small-business', 'developers'],
		highlights: ['Public, private, people, groups and apps', 'Inherit permissions down the tree', 'Comment-only and write capabilities'],
		screen: 'things',
		answers: ['google-drive', 'notion', 'airtable']
	},
	{
		key: 'hidden-links',
		name: 'Hidden links',
		emoji: '🫥',
		route: '/things',
		tagline: 'Unlisted sharing with a rotating secret link.',
		description: 'Mark a thing hidden and share an owner-only link key; rotate the key any time to cut off old links without touching the data.',
		category: 'data',
		audiences: ['creators', 'teams', 'families'],
		highlights: ['Unlisted, not public', 'Rotate the key to revoke', 'Works for posts, pages and files'],
		screen: 'things'
	},
	{
		key: 'custom-audiences',
		name: 'Custom audiences',
		emoji: '🎭',
		route: '/things',
		tagline: 'Pick exactly who sees each post or thing.',
		description: 'Compose an audience from named people, groups and capability levels like comment-only or write, then reuse it across posts.',
		category: 'data',
		audiences: ['creators', 'families', 'teams'],
		highlights: ['Search people to add them', 'Comment-only or write access per person', 'Groups for recurring audiences'],
		screen: 'feed',
		answers: ['instagram', 'facebook']
	},
	{
		key: 'sensitive-reveal',
		name: 'Sensitive value reveal',
		emoji: '🙈',
		route: '/things',
		tagline: 'Secrets stay masked until you confirm.',
		description: 'Mark values sensitive and they render masked; revealing one asks for your password again so a walk-by never leaks a token.',
		category: 'data',
		audiences: ['developers', 'power-users', 'small-business'],
		highlights: ['Masked in every view', 'Password confirmation to reveal', 'Audit-friendly by design'],
		screen: 'things'
	},
	{
		key: 'schemas',
		name: 'Schemas',
		emoji: '💎',
		route: '/schemas',
		tagline: 'Describe a shape once, reuse it everywhere.',
		description: 'Browse and build schemas that describe kinds of things, compose them, and render them with the registry of built-in projections.',
		category: 'data',
		audiences: ['developers', 'power-users', 'researchers', 'teams'],
		highlights: ['Compose schemas from other schemas', 'Built-in projections render each kind', 'Reference docs live at /docs/schemas'],
		screen: 'components',
		answers: ['airtable', 'notion']
	},
	{
		key: 'raw-workbench',
		name: 'Raw query workbench',
		emoji: '🧪',
		route: '/raw',
		tagline: 'Query your own data like a developer.',
		description: 'A MongoDB-style query surface over your things, for the moments a tree is not enough and you want the raw rows.',
		category: 'developer',
		audiences: ['developers', 'power-users', 'researchers'],
		highlights: ['Filter, project and sort', 'See the raw document shape', 'Same permissions as everywhere else'],
		screen: 'developer'
	},

	// -------------------------------------------------------------- social
	{
		key: 'feed',
		name: 'Feed',
		emoji: '📰',
		route: '/feed',
		tagline: 'A social feed where every post is a thing you own.',
		description: 'Compose posts with attachments, polls and audiences, follow people, and read a feed powered by swappable feed algorithms.',
		category: 'social',
		audiences: ['creators', 'families', 'hobbyists', 'teams'],
		highlights: ['Composer with media, polls and audiences', 'Pluggable feed algorithms', 'Posts are things: exportable, linkable, yours'],
		screen: 'feed',
		answers: ['twitter', 'facebook', 'instagram', 'mastodon']
	},
	{
		key: 'posts-comments',
		name: 'Posts and comments',
		emoji: '💬',
		route: '/feed',
		tagline: 'Comments are posts too, with their own permalinks.',
		description: 'Every comment is a full post with reactions, attachments and a /post/:id permalink, so threads never lose context.',
		category: 'social',
		audiences: ['creators', 'teams', 'families'],
		highlights: ['Threaded replies with full posts', 'Permalinks for every reply', 'Edit with attachment sync'],
		screen: 'feed',
		answers: ['twitter', 'reddit']
	},
	{
		key: 'reactions',
		name: 'Emoji reactions',
		emoji: '❤️',
		route: '/feed',
		tagline: 'Long-press for the whole emoji picker.',
		description: 'Tap to react, long-press for any emoji, with instant optimistic toggles and a recently-used row that paints from cache.',
		category: 'social',
		audiences: ['creators', 'families', 'hobbyists'],
		highlights: ['Any emoji, not six', 'Instant optimistic toggles', 'Recently used remembered per device'],
		screen: 'feed',
		answers: ['facebook', 'slack']
	},
	{
		key: 'explore-trending',
		name: 'Explore',
		emoji: '🔥',
		route: '/explore',
		tagline: 'A public trending board, no login needed.',
		description: 'Explore surfaces trending public posts, hashtags and people, readable by guests and shareable as a link.',
		category: 'social',
		audiences: ['creators', 'hobbyists', 'students'],
		highlights: ['Guest-readable trending board', 'Hashtag pages', 'Share any trend as a link'],
		screen: 'feed',
		answers: ['twitter', 'instagram']
	},
	{
		key: 'hashtags',
		name: 'Hashtags',
		emoji: '#️⃣',
		route: '/explore',
		tagline: 'Tag it once, find it forever.',
		description: 'Inline hashtags become links and pages, so a topic across posts and people is one tap away.',
		category: 'social',
		audiences: ['creators', 'hobbyists', 'educators'],
		highlights: ['Inline tags become links', 'Topic pages aggregate posts', 'Works with emoji tags'],
		screen: 'feed'
	},
	{
		key: 'mentions',
		name: '@mentions',
		emoji: '📣',
		route: '/feed',
		tagline: 'Pull someone into the conversation.',
		description: 'Type @ to mention a person in posts and comments; mentions link to profiles and can notify.',
		category: 'social',
		audiences: ['teams', 'families', 'creators'],
		highlights: ['@ autocompletes people', 'Mentions link to profiles', 'Notification preferences per channel'],
		screen: 'feed'
	},
	{
		key: 'polls',
		name: 'Polls',
		emoji: '📊',
		route: '/feed',
		tagline: 'Ask your people, count the votes as things.',
		description: 'Add a poll to any post; each vote is its own relational thing so tallies stay accurate and auditable.',
		category: 'social',
		audiences: ['creators', 'teams', 'educators', 'families'],
		highlights: ['Polls inside any post', 'Votes stored relationally', 'Live tallies'],
		screen: 'feed',
		answers: ['twitter', 'slack']
	},
	{
		key: 'profiles',
		name: 'Profiles',
		emoji: '👤',
		route: '/profile',
		tagline: 'A profile that wears your theme.',
		description: 'Profiles show posts, media and details, with per-profile theme try-on and media galleries that link to file pages.',
		category: 'social',
		audiences: ['creators', 'designers', 'hobbyists'],
		highlights: ['Media gallery of your uploads', 'Theme try-on per profile', 'Details are things you control'],
		screen: 'profile',
		answers: ['linktree', 'instagram']
	},
	{
		key: 'messages',
		name: 'Messages: Spaces and Chats',
		emoji: '💬',
		route: '/messages',
		tagline: 'Chats and spaces, on top of your things.',
		description: 'Direct chats and shared spaces with last-message previews, requests for strangers and the same permission model as everything else.',
		category: 'social',
		audiences: ['teams', 'families', 'creators', 'small-business'],
		highlights: ['Spaces for groups, chats for people', 'Message requests keep strangers out', 'Every message is a thing'],
		screen: 'messages',
		answers: ['slack', 'discord', 'whatsapp']
	},
	{
		key: 'message-requests',
		name: 'Message requests',
		emoji: '💌',
		route: '/messages?view=requests',
		tagline: 'Strangers ask first.',
		description: 'People you have not talked to land in a requests view you can accept or ignore, so your inbox stays yours.',
		category: 'social',
		audiences: ['creators', 'families', 'students'],
		highlights: ['Separate requests inbox', 'Accept or ignore in one tap', 'No unsolicited pings'],
		screen: 'messages',
		answers: ['instagram', 'discord']
	},
	{
		key: 'attachments-media',
		name: 'Attachments and media pages',
		emoji: '🖼️',
		route: '/feed',
		tagline: 'Every file is a thing with its own page.',
		description: 'Uploads become attachment things with detected types, a /media/:id page, comments and reactions, and a lightbox in the feed.',
		category: 'social',
		audiences: ['creators', 'designers', 'families'],
		highlights: ['Images, video and files', 'Comments and reactions on files', 'Lightbox with deep links'],
		screen: 'feed',
		answers: ['google-drive', 'dropbox']
	},
	{
		key: 'inline-video',
		name: 'Inline video',
		emoji: '🎬',
		route: '/feed',
		tagline: 'MP4, WebM, MOV and more, playing in the feed.',
		description: 'Drop a video and it plays inline, with container detection that also catches MOV files that are secretly MP4.',
		category: 'social',
		audiences: ['creators', 'families', 'hobbyists'],
		highlights: ['Plays inline on web and iOS', 'Broad container allowlist', 'Detected types, not guessed extensions'],
		screen: 'feed'
	},
	{
		key: 'attachment-reorder',
		name: 'Drag-to-reorder attachments',
		emoji: '↕️',
		route: '/feed',
		tagline: 'Put your best photo first.',
		description: 'Reorder attachments by dragging in the composer and in edit mode; the order is saved as a pure permutation.',
		category: 'social',
		audiences: ['creators', 'designers'],
		highlights: ['Drag in the composer', 'Reorder after posting', 'Order saved exactly'],
		screen: 'feed'
	},
	{
		key: 'og-link-previews',
		name: 'Rich link previews',
		emoji: '🪟',
		route: '/feed',
		tagline: 'Posts unfurl beautifully everywhere.',
		description: 'Shared posts and pages carry Open Graph images and metadata so links look right in chats and social apps.',
		category: 'social',
		audiences: ['creators', 'founders', 'teams'],
		highlights: ['OG image per post', 'Titles and descriptions filled in', 'Works for public pages too'],
		screen: 'feed'
	},
	{
		key: 'rss',
		name: 'RSS feeds',
		emoji: '📡',
		route: '/feed',
		tagline: 'Your posts, in any reader.',
		description: 'Public feeds are available as RSS so readers, automations and newsletters can subscribe without an account.',
		category: 'social',
		audiences: ['creators', 'developers', 'researchers'],
		highlights: ['RSS for public feeds', 'No account needed to subscribe', 'Plays well with automations'],
		screen: 'feed',
		answers: ['substack']
	},
	{
		key: 'activity-heatmap',
		name: 'Activity heatmap',
		emoji: '🟩',
		route: '/profile',
		tagline: 'See your year of things at a glance.',
		description: 'A GitHub-style heatmap of your activity across posts and things, rendered on your profile.',
		category: 'social',
		audiences: ['creators', 'students', 'hobbyists'],
		highlights: ['Daily activity squares', 'Posts and things counted', 'Rainbow-tinted intensity'],
		screen: 'profile',
		answers: ['github']
	},
	{
		key: 'notifications',
		name: 'Notifications',
		emoji: '🔔',
		route: '/settings',
		tagline: 'Push and email, per event, your rules.',
		description: 'A preference matrix decides which events reach you by push or email, delivered through the owned email stack.',
		category: 'account',
		audiences: ['teams', 'creators', 'families'],
		highlights: ['Per-event push and email toggles', 'Owned email delivery', 'Bell with unread state'],
		screen: 'settings'
	},
	{
		key: 'external-sources',
		name: 'Connected sources',
		emoji: '📺',
		route: '/settings',
		tagline: 'Bring outside feeds into your things.',
		description: 'Link external accounts and sources so their posts appear as things you can react to, organise and share.',
		category: 'social',
		audiences: ['creators', 'hobbyists', 'researchers'],
		highlights: ['Relational per-source membership', 'Virtual channel lists', 'Same feed, more sources'],
		screen: 'feed'
	},

	// ------------------------------------------------------------- builder
	{
		key: 'webpage-builder',
		name: 'Webpage builder',
		emoji: '🧱',
		route: '/builder',
		tagline: 'Build real pages from blocks, publish in a click.',
		description: 'A block-based builder with a bounded block tree, drag reorder, inline text editing, media drops and a true WYSIWYG canvas.',
		category: 'builder',
		audiences: ['creators', 'designers', 'small-business', 'founders'],
		highlights: ['Drag blocks, edit inline', 'Media drop and paste to upload', 'Publish to /p/ instantly'],
		screen: 'builder',
		answers: ['webflow', 'wordpress', 'squarespace', 'carrd', 'linktree']
	},
	{
		key: 'published-pages',
		name: 'Published pages',
		emoji: '🌐',
		route: '/builder',
		tagline: 'Public pages with clean short URLs.',
		description: 'Publish any built page at /p/<id>; visitors need no account and the page serves its media anonymously through inherited permissions.',
		category: 'builder',
		audiences: ['creators', 'small-business', 'founders'],
		highlights: ['Anonymous visitors welcome', 'Media inherits page permissions', 'Fork any public page you like'],
		screen: 'builder',
		answers: ['carrd', 'linktree']
	},
	{
		key: 'site-edit-mode',
		name: 'Edit the site in place',
		emoji: '✏️',
		route: '/builder',
		tagline: 'The landing page is a page you can edit.',
		description: 'Thingtime’s own routes render from block compositions, so site pages open in the same builder and stay pixel-identical.',
		category: 'builder',
		audiences: ['designers', 'developers', 'founders'],
		highlights: ['Routes are block compositions', 'Same builder for site and user pages', 'Pixel-identical between edit and view'],
		screen: 'builder'
	},
	{
		key: 'components-library',
		name: 'Components library',
		emoji: '🧩',
		route: '/components',
		tagline: 'A thousand components, each with docs and a demo.',
		description: 'Browse a large catalog of component things with a template DSL, deep-linked pages and generated docs twins.',
		category: 'builder',
		audiences: ['designers', 'developers', 'creators'],
		highlights: ['Every component has a page', 'Template args with safe caps', 'Docs generated from the same source'],
		screen: 'components',
		answers: ['storybook', 'webflow']
	},
	{
		key: 'actions',
		name: 'Actions',
		emoji: '⚡',
		route: '/actions',
		tagline: 'Small declarative programs with hard limits.',
		description: 'Actions run capability-bounded steps (compute, each, when, delete) over your data things with a shared budget and run records.',
		category: 'builder',
		audiences: ['developers', 'power-users', 'small-business'],
		highlights: ['Closed vocabulary, no arbitrary code', 'Run panel with history', 'Budgets stop runaway loops'],
		screen: 'developer',
		answers: ['zapier']
	},
	{
		key: 'app-suites',
		name: 'Installable app suites',
		emoji: '📲',
		route: '/components',
		tagline: 'Multi-page apps you install into your account.',
		description: 'App suites bundle pages, schemas, components and actions; install one and its pages resolve under your own /p/ keys.',
		category: 'builder',
		audiences: ['creators', 'small-business', 'hobbyists'],
		highlights: ['Pages, schemas and actions together', 'Install with one click', 'Twins resolve to your copy'],
		screen: 'components'
	},
	{
		key: 'demo-library',
		name: 'Demo page library',
		emoji: '🎪',
		route: '/builder',
		tagline: 'Hundreds of starting points, one click to fork.',
		description: 'A library of generated demo pages and behaviour suites shows what blocks can do and forks into your account as a starting point.',
		category: 'builder',
		audiences: ['creators', 'designers', 'students'],
		highlights: ['300+ demo pages', 'Behaviour suites for actions and data', 'Fork into your own draft'],
		screen: 'builder'
	},
	{
		key: 'figma-layer',
		name: 'Design controls',
		emoji: '🎚️',
		route: '/builder',
		tagline: 'Figma-style CSS controls on every block.',
		description: 'An inspector with spacing, typography, colour and layout controls, plus tag, html and media blocks with safety gates.',
		category: 'builder',
		audiences: ['designers', 'creators'],
		highlights: ['Spacing and typography inspector', 'Grid and flex layout zones', 'Safe HTML blocks'],
		screen: 'builder',
		answers: ['figma', 'webflow']
	},
	{
		key: 'rich-text',
		name: 'Rich text editing',
		emoji: '📝',
		route: '/feed',
		tagline: 'Headings, lists and links, sanitised on entry.',
		description: 'A block-style rich text editor for posts and pages, with inline editing and HTML scrubbing so pasted content stays safe.',
		category: 'builder',
		audiences: ['creators', 'educators', 'teams'],
		highlights: ['Block-style editing', 'Paste HTML safely', 'Same editor in posts and pages'],
		screen: 'feed'
	},
	{
		key: 'drop-to-upload',
		name: 'Drop or paste to upload',
		emoji: '📤',
		route: '/builder',
		tagline: 'Drop a file anywhere it makes sense.',
		description: 'Drag files onto the composer or the builder canvas, or paste an image, and it uploads with deduplication and a sensible cap.',
		category: 'builder',
		audiences: ['creators', 'designers', 'families'],
		highlights: ['Drop on composer or canvas', 'Paste screenshots directly', 'Duplicate uploads deduped'],
		screen: 'builder'
	},

	// -------------------------------------------------------------- design
	{
		key: 'themes',
		name: 'Themes',
		emoji: '🎨',
		route: '/themes',
		tagline: 'Fable, Prism, or a theme you invent.',
		description: 'Every colour, font, radius and shadow is a token you can edit; save named themes, share them by id and apply them anywhere.',
		category: 'design',
		audiences: ['designers', 'creators', 'power-users'],
		highlights: ['Two built-in presets', 'Edit any token live', 'Share themes by id'],
		screen: 'themes',
		answers: ['notion', 'obsidian']
	},
	{
		key: 'theme-gallery',
		name: 'Theme gallery',
		emoji: '🖼️',
		route: '/themes/gallery',
		tagline: 'Try on a look before you commit.',
		description: 'A gallery of shared themes with instant try-on, so your feed, profile and pages can change mood in a click.',
		category: 'design',
		audiences: ['designers', 'creators', 'hobbyists'],
		highlights: ['Instant try-on', 'Apply from the gallery', 'Profiles can wear their own theme'],
		screen: 'themes'
	},
	{
		key: 'rainbow-design-language',
		name: 'The rainbow design language',
		emoji: '🌈',
		route: '/docs/design-system',
		tagline: 'A five-stop rainbow that runs through everything.',
		description: 'Voxel logo, animated gradient headlines, depth guides and toasts all share one palette and one set of CSS tokens.',
		category: 'design',
		audiences: ['designers', 'creators', 'founders'],
		highlights: ['One palette, every surface', 'Motion respects reduced-motion', 'Tokens are user-themable'],
		screen: 'themes'
	},
	{
		key: 'design-system-docs',
		name: 'Design system storybook',
		emoji: '📐',
		route: '/docs/design-system',
		tagline: 'Every primitive, documented with live stories.',
		description: 'A storybook-style reference of scaffolds, typography, clearance, menus and controls, rendered from the real components.',
		category: 'design',
		audiences: ['designers', 'developers'],
		highlights: ['Live stories, not screenshots', 'Page scaffolds and clearance rules', 'Copyable idioms'],
		screen: 'components',
		answers: ['storybook']
	},
	{
		key: 'branding-kit',
		name: 'Brand resources',
		emoji: '🧷',
		route: '/branding',
		tagline: 'Logos in every size, exported on the fly.',
		description: 'The /branding page offers the voxel wordmark and icon as ready-made PNG and SVG files plus a custom exporter with padding and background.',
		category: 'design',
		audiences: ['designers', 'creators', 'founders'],
		highlights: ['PNG and SVG from 10px to 10k', 'Custom padding and background', 'Press kit included'],
		screen: 'themes'
	},
	{
		key: 'lopu-toasts',
		name: 'Lopu',
		emoji: '🦄',
		route: '/feed',
		tagline: 'A friendly unicorn tells you what just happened.',
		description: 'All notifications flow through the Lopu toast with a rainbow border, streaming messages and gentle motion instead of raw alerts.',
		category: 'ai',
		audiences: ['creators', 'families', 'power-users'],
		highlights: ['One toast system everywhere', 'Streams long messages', 'Dismiss or stack'],
		screen: 'feed'
	},

	// ----------------------------------------------------------- developer
	{
		key: 'open-api',
		name: 'Open REST API',
		emoji: '🔌',
		route: '/docs/api',
		tagline: 'Everything the app does, you can do with curl.',
		description: 'The UI is a client of the same /api/v1 endpoints you get, with cookie or bearer auth and JSON in and out.',
		category: 'developer',
		audiences: ['developers', 'founders', 'researchers'],
		highlights: ['UI and API share one code path', 'Bearer tokens for scripts', 'Versioned under /api/v1'],
		screen: 'developer',
		answers: ['notion', 'airtable', 'firebase', 'supabase']
	},
	{
		key: 'api-docs',
		name: 'Interactive API docs',
		emoji: '📚',
		route: '/docs/api',
		tagline: 'Docs generated from the route registry itself.',
		description: 'Every endpoint is documented from the same registry Nitro routes are built from, so the docs cannot drift from reality.',
		category: 'developer',
		audiences: ['developers'],
		highlights: ['Registry-driven, never stale', 'Grouped by family', 'Smoke tests generated per endpoint'],
		screen: 'developer'
	},
	{
		key: 'capability-manifest',
		name: 'Capability manifest',
		emoji: '🧾',
		route: '/docs/api',
		tagline: 'Clients negotiate features by semver, not by guessing.',
		description: 'A machine-readable manifest lists every endpoint as a versioned feature so clients check compatibility before they persist anything.',
		category: 'developer',
		audiences: ['developers', 'teams'],
		highlights: ['Semver per feature', 'Generated from the live route map', 'Clients fail closed on mismatch'],
		screen: 'developer'
	},
	{
		key: 'personal-access-tokens',
		name: 'Personal access tokens',
		emoji: '🗝️',
		route: '/settings',
		tagline: 'Scoped tokens for scripts, bots and apps.',
		description: 'Mint tokens with exact scopes from a catalog; default-deny means a token can only do what you ticked.',
		category: 'developer',
		audiences: ['developers', 'power-users', 'small-business'],
		highlights: ['Exact scopes, default deny', 'Revoke any time', 'Works with MCP and ChatGPT'],
		screen: 'settings',
		answers: ['github']
	},
	{
		key: 'login-with-thingtime',
		name: 'Login with Thingtime',
		emoji: '🔑',
		route: '/docs/embed',
		tagline: 'OAuth for your app in one popup.',
		description: 'Any origin can offer Login with Thingtime; users see a consent screen and your app gets a per-origin token with the scopes it asked for.',
		category: 'apps',
		audiences: ['developers', 'founders', 'small-business'],
		highlights: ['Popup consent flow', 'Per-origin token binding', 'Desktop and mobile handoff'],
		screen: 'developer',
		answers: ['firebase']
	},
	{
		key: 'embed-sdk',
		name: 'Embed SDK',
		emoji: '🧷',
		route: '/docs/embed',
		tagline: 'Drop Thingtime into any site with one script.',
		description: 'A stable copy-paste SDK URL that adds login, things and posting to your own site, with a protocol that revalidates itself.',
		category: 'apps',
		audiences: ['developers', 'small-business', 'creators'],
		highlights: ['One script tag', 'Stable URL, fresh protocol', 'Login, read and write'],
		screen: 'developer'
	},
	{
		key: 'mcp-connector',
		name: 'MCP connector',
		emoji: '🤖',
		route: '/docs/mcp',
		tagline: 'Let Claude and ChatGPT read and write your things.',
		description: 'A Model Context Protocol server with 30+ tools, OAuth with PKCE and per-tool confirmations for writes.',
		category: 'ai',
		audiences: ['developers', 'power-users', 'researchers', 'founders'],
		highlights: ['30+ tools for things, posts and comments', 'OAuth with PKCE', 'Writes ask for confirmation'],
		screen: 'developer',
		answers: ['notion', 'zapier']
	},
	{
		key: 'chatgpt-app',
		name: 'ChatGPT app',
		emoji: '💡',
		route: '/docs/mcp',
		tagline: 'Talk to your data from ChatGPT.',
		description: 'Connect Thingtime in ChatGPT, log in from mobile through a relay, and list, read and search your things in conversation.',
		category: 'ai',
		audiences: ['power-users', 'students', 'researchers'],
		highlights: ['Mobile OAuth relay login', 'Multiple named accounts', 'Reads and scoped writes'],
		screen: 'developer'
	},
	{
		key: 'app-namespaces',
		name: 'App data namespaces',
		emoji: '📦',
		route: '/apps',
		tagline: 'Every connected app gets its own shelf.',
		description: 'Apps store data under their own namespace with exact scopes; browse everything each app keeps for you at /apps.',
		category: 'apps',
		audiences: ['developers', 'power-users'],
		highlights: ['Per-app storage', 'Exact scopes, no ancestors', 'Browse and revoke'],
		screen: 'settings'
	},
	{
		key: 'api-tests',
		name: 'In-app API tests',
		emoji: '✅',
		route: '/tests',
		tagline: 'Run the API test suite from the app itself.',
		description: 'A /tests page runs the live API tests against the current deployment and shows results inline.',
		category: 'developer',
		audiences: ['developers'],
		highlights: ['Run against any deployment', 'Docs-generated smoke tests', 'Results inline'],
		screen: 'developer'
	},
	{
		key: 'deployment-status',
		name: 'Deployment status',
		emoji: '🚀',
		route: '/status',
		tagline: 'See what is deployed, where, and how it is doing.',
		description: 'Status and Vercel pages show branch, build, preview and production deployments with links into the dashboard.',
		category: 'admin',
		audiences: ['developers', 'teams'],
		highlights: ['Branch-aware previews', 'Build and runtime facts', 'Dashboard links'],
		screen: 'developer'
	},
	{
		key: 'mongodb-status',
		name: 'MongoDB status',
		emoji: '🌱',
		route: '/mongodb-status',
		tagline: 'Collections, indexes and versions, in the app.',
		description: 'An operator view of collections, index budgets and schema versions, plus endpoint configuration for other deployments.',
		category: 'admin',
		audiences: ['developers'],
		highlights: ['Index budget in view', 'Versioned collections', 'Endpoint config'],
		screen: 'developer'
	},
	{
		key: 'migrations',
		name: 'Migrations console',
		emoji: '🛠️',
		route: '/migrations',
		tagline: 'Run and audit data migrations safely.',
		description: 'Admins run named migrations with diagnostics, honest partial-failure receipts and a run history.',
		category: 'admin',
		audiences: ['developers'],
		highlights: ['Named migrations', 'Partial failure receipts', 'Run history'],
		screen: 'developer'
	},
	{
		key: 'deployment-peers',
		name: 'Deployment peers',
		emoji: '🕸️',
		route: '/peers',
		tagline: 'Link deployments and sync across them.',
		description: 'Cross-deployment sync uses secure-blob tokens and share ids with fail-closed limits, so previews and production can talk safely.',
		category: 'admin',
		audiences: ['developers', 'teams'],
		highlights: ['Secure peer tokens', 'Fail-closed limits', 'Preview to production sync'],
		screen: 'developer'
	},
	{
		key: 'crypto-tools',
		name: 'Crypto tools',
		emoji: '🔒',
		route: '/crypto',
		tagline: 'Hash, sign and verify without leaving the app.',
		description: 'Developer utilities for hashing and encryption checks, handy when testing secure blobs and signed handoffs.',
		category: 'developer',
		audiences: ['developers'],
		highlights: ['Hash and verify', 'Secure blob checks', 'No data leaves the browser'],
		screen: 'developer'
	},

	// ------------------------------------------------------------------ ai
	{
		key: 'lopu-ai',
		name: 'Lopu AI',
		emoji: '🧠',
		route: '/feed',
		tagline: 'An assistant that muses about your things.',
		description: 'Lopu streams AI musings and answers into the toast system, backed by a provider-aware model waterfall.',
		category: 'ai',
		audiences: ['power-users', 'creators', 'students'],
		highlights: ['Streams as it thinks', 'Knows your things', 'Same toast, no new UI'],
		screen: 'feed'
	},
	{
		key: 'ai-model-waterfall',
		name: 'AI model waterfall',
		emoji: '🌊',
		route: '/admin',
		tagline: 'Claude and OpenAI models, in a fallback chain.',
		description: 'A composed model:effort:fast id over a catalog of Claude and OpenAI models with an admin control plane for routing.',
		category: 'ai',
		audiences: ['developers', 'founders'],
		highlights: ['Unlimited fallback chain', '33-model catalog', 'Admin control plane'],
		screen: 'developer'
	},

	// ------------------------------------------------------------- account
	{
		key: 'passkeys',
		name: 'Passkeys',
		emoji: '🔏',
		route: '/settings',
		tagline: 'Sign in with your face or fingerprint.',
		description: 'WebAuthn passkeys stored as protected things, with auto-login hints that resolve live across deployments.',
		category: 'account',
		audiences: ['power-users', 'families', 'teams'],
		highlights: ['Face, touch or security key', 'No password to phish', 'Works across deployments'],
		screen: 'settings'
	},
	{
		key: 'federated-login',
		name: 'Federated login',
		emoji: '🛰️',
		route: '/login',
		tagline: 'One account across previews and production.',
		description: 'Single-use handoff codes and family-origin account hints let you move between deployments without logging in again.',
		category: 'account',
		audiences: ['developers', 'teams'],
		highlights: ['Single-use handoff codes', 'Replay revokes', 'Cross-database fail-closed'],
		screen: 'settings'
	},
	{
		key: 'account-switcher',
		name: 'Account switcher',
		emoji: '🔄',
		route: '/settings',
		tagline: 'Two accounts, one tap apart.',
		description: 'Keep several accounts signed in and switch instantly; the roster paints from cache so it never flashes a loading state.',
		category: 'account',
		audiences: ['creators', 'small-business', 'power-users'],
		highlights: ['Instant switch', 'Roster from cache', 'Per-account view caches'],
		screen: 'settings',
		answers: ['instagram', 'twitter']
	},
	{
		key: 'try-without-signup',
		name: 'Try it without signing up',
		emoji: '🎈',
		route: '/register',
		tagline: 'Start creating first, register when it matters.',
		description: 'A temporary user bootstraps on first visit so you can post and build immediately, then claim the account by registering.',
		category: 'account',
		audiences: ['students', 'hobbyists', 'creators'],
		highlights: ['No form before first post', 'Claim the account later', 'Nothing lost on register'],
		screen: 'feed'
	},
	{
		key: 'email-flows',
		name: 'Email verification and reset',
		emoji: '✉️',
		route: '/login',
		tagline: 'Verification, resets and OTPs from an owned stack.',
		description: 'Verification links, password resets and one-time codes flow through an outbox with suppressions and an audit trail.',
		category: 'account',
		audiences: ['teams', 'small-business'],
		highlights: ['Owned outbox', 'Suppressions and audit', 'Transactional stream'],
		screen: 'settings'
	},
	{
		key: 'quotas-and-tiers',
		name: 'Plans and quotas',
		emoji: '💳',
		route: '/settings',
		tagline: 'Fair limits, clear upgrades.',
		description: 'Subscription tiers, pay-as-you-go and per-account overrides govern storage and rate limits, visible in settings and admin.',
		category: 'account',
		audiences: ['founders', 'small-business', 'teams'],
		highlights: ['Tiers and overrides', 'Quota visible in app', 'Rate limits that fail audibly'],
		screen: 'settings'
	},

	// ---------------------------------------------------------------- apps
	{
		key: 'ios-app',
		name: 'iOS app',
		emoji: '📱',
		route: '/welcome',
		tagline: 'Thingtime in your pocket, native shell included.',
		description: 'A native iOS app wraps the web experience with safe areas, native bridges and TestFlight releases.',
		category: 'mobile',
		audiences: ['creators', 'families', 'hobbyists'],
		highlights: ['Native shell with safe areas', 'Same account everywhere', 'TestFlight builds'],
		screen: 'feed'
	},
	{
		key: 'raycast-extension',
		name: 'Raycast extension',
		emoji: '⌨️',
		route: '/docs',
		tagline: 'Your things from the command bar.',
		description: 'Search and open things from Raycast on macOS without opening a browser tab.',
		category: 'mobile',
		audiences: ['developers', 'power-users'],
		highlights: ['Search from Raycast', 'Open in the app', 'Keyboard-first'],
		screen: 'search'
	},
	{
		key: 'commander-desktop',
		name: 'Commander for macOS',
		emoji: '🖥️',
		route: '/docs',
		tagline: 'A native desktop companion with Developer ID signing.',
		description: 'Commander is a signed macOS app with a desktop UI, emoji picker and OAuth handoff into your Thingtime account.',
		category: 'mobile',
		audiences: ['developers', 'power-users'],
		highlights: ['Signed and notarised', 'Desktop OAuth handoff', 'Emoji picker that learns'],
		screen: 'search'
	},
	{
		key: 'desktop-app',
		name: 'Desktop app',
		emoji: '💻',
		route: '/docs',
		tagline: 'Thingtime as a window, with auto updates.',
		description: 'An Electron shell with an update manager and a native bridge for the moments a browser tab is not enough.',
		category: 'mobile',
		audiences: ['power-users', 'teams'],
		highlights: ['Auto updates', 'Native bridge', 'Same web app'],
		screen: 'feed'
	},
	{
		key: 'keyboard-shortcuts',
		name: 'Keyboard shortcuts',
		emoji: '⌨️',
		route: '/settings',
		tagline: 'Move faster without the mouse.',
		description: 'Shortcuts for navigation, composing and the command palette, listed in settings and respected everywhere.',
		category: 'core',
		audiences: ['power-users', 'developers'],
		highlights: ['Command palette with ⌘P', 'Compose and navigate', 'Listed in settings'],
		screen: 'search'
	},
	{
		key: 'command-palette',
		name: 'Command palette',
		emoji: '🔮',
		route: '/search',
		tagline: 'Press ⌘P and imagine.',
		description: 'The Imagine pill opens a palette that searches things and commands with emoji, mono paths and previews.',
		category: 'core',
		audiences: ['power-users', 'developers', 'designers'],
		highlights: ['⌘P from anywhere', 'Things and commands together', 'Previews inline'],
		screen: 'search'
	},
	{
		key: 'drawer-navigation',
		name: 'Drawer navigation',
		emoji: '🧭',
		route: '/feed',
		tagline: 'A slide-out map of the whole app.',
		description: 'A reorderable drawer groups every destination into hubs you can pin, reorder and keep open.',
		category: 'core',
		audiences: ['power-users', 'families', 'students'],
		highlights: ['Reorder hubs', 'Keep sections open', 'Flush to the edge on mobile'],
		screen: 'feed'
	},

	// --------------------------------------------------------------- admin
	{
		key: 'admin-dashboard',
		name: 'Admin dashboard',
		emoji: '🛡️',
		route: '/admin',
		tagline: 'Run the whole instance from one page.',
		description: 'Admins manage tiers, overrides, integrations, CI control and account links from a sectioned dashboard.',
		category: 'admin',
		audiences: ['developers', 'founders'],
		highlights: ['Tiers and overrides', 'Integrations', 'CI control'],
		screen: 'developer'
	},
	{
		key: 'moderation',
		name: 'Upload moderation',
		emoji: '🧹',
		route: '/admin',
		tagline: 'Approve public uploads before they go wide.',
		description: 'Tri-state public and private upload flags with approval scopes decide what appears without review.',
		category: 'admin',
		audiences: ['founders', 'teams', 'educators'],
		highlights: ['Public and private scopes', 'Approve or hold', 'Detected content types'],
		screen: 'developer'
	},
	{
		key: 'rate-limiting',
		name: 'Rate limiting',
		emoji: '🚦',
		route: '/admin',
		tagline: 'Limits that protect the good actors.',
		description: 'Per-route rate limits with audible failures and quota telemetry in a dedicated control satellite.',
		category: 'admin',
		audiences: ['developers', 'founders'],
		highlights: ['Per-route limits', 'Audible failures', 'Telemetry with retention'],
		screen: 'developer'
	},
	{
		key: 'self-hosting',
		name: 'Self-host or fork',
		emoji: '🏡',
		route: '/docs',
		tagline: 'Your own Thingtime, your own database.',
		description: 'Fork the repository, point it at your MongoDB and deploy to Vercel; previews are branch-scoped and documented for forks.',
		category: 'developer',
		audiences: ['developers', 'founders', 'researchers'],
		highlights: ['One MongoDB, one config', 'Vercel-ready builds', 'Fork-safe README'],
		screen: 'developer',
		answers: ['notion', 'firebase', 'supabase']
	},

	// ------------------------------------------------------- more social
	{
		key: 'saved-library',
		name: 'Saved library',
		emoji: '🔖',
		route: '/saved',
		tagline: 'Bookmark anything, find it in one place.',
		description: 'Save posts, files and things into your own library, browsable at /saved with the same permissions as the originals.',
		category: 'social',
		audiences: ['students', 'researchers', 'creators', 'hobbyists'],
		highlights: ['Save posts, files and things', 'One library, many kinds', 'Private to you'],
		screen: 'feed',
		answers: ['pinterest']
	},
	{
		key: 'feed-algorithms',
		name: 'Pick your feed algorithm',
		emoji: '🧮',
		route: '/feed',
		tagline: 'Choose how your feed thinks, or train it.',
		description: 'The feed has an algorithm picker; the active algorithm learns from how you scroll and you can switch any time.',
		category: 'social',
		audiences: ['creators', 'power-users', 'researchers'],
		highlights: ['Switch algorithms in one tap', 'Learns from engagement', 'No hidden ranking'],
		screen: 'feed',
		answers: ['twitter', 'instagram', 'tiktok']
	},
	{
		key: 'reposts-quotes',
		name: 'Reposts and quotes',
		emoji: '🔁',
		route: '/feed',
		tagline: 'Repost instantly or quote with a caption.',
		description: 'An X-style split control gives an instant repost or a quote post with caption and audience, applied optimistically.',
		category: 'social',
		audiences: ['creators', 'hobbyists', 'teams'],
		highlights: ['Instant repost', 'Quote with caption', 'Choose the audience'],
		screen: 'feed',
		answers: ['twitter', 'mastodon']
	},
	{
		key: 'emoji-picker',
		name: 'Emoji everything',
		emoji: '😄',
		route: '/feed',
		tagline: 'A picker that learns which emoji you love.',
		description: 'Search emoji by name or tone, see recently used first, and reuse the same picker in reactions, posts and messages.',
		category: 'social',
		audiences: ['creators', 'families', 'hobbyists'],
		highlights: ['Search by name or tone', 'Recently used from cache', 'Same picker everywhere'],
		screen: 'feed'
	},
	{
		key: 'agent-chats',
		name: 'Agents in your chats',
		emoji: '🛸',
		route: '/messages',
		tagline: 'Talk to an AI agent inside Messages.',
		description: 'Agent conversations show live activity in a chat, with roles for you and the assistant and the same message things underneath.',
		category: 'ai',
		audiences: ['power-users', 'developers', 'students'],
		highlights: ['Live agent activity', 'Messages stay things', 'Same inbox as people'],
		screen: 'messages'
	},
	{
		key: 'devices-hub',
		name: 'Devices',
		emoji: '📟',
		route: '/settings',
		tagline: 'Approve, name and control your devices.',
		description: 'Paired devices get cards with approval, power, network and audio controls plus a command timeline.',
		category: 'account',
		audiences: ['power-users', 'developers', 'families'],
		highlights: ['Approve new devices', 'Command timeline', 'Power and network controls'],
		screen: 'settings'
	},
	{
		key: 'welcome-onboarding',
		name: 'Welcome tour',
		emoji: '✨',
		route: '/welcome',
		tagline: 'A first run that shows, not tells.',
		description: 'New accounts land on a welcome page built from the same block sections as the site, so the tour is always current.',
		category: 'account',
		audiences: ['students', 'families', 'hobbyists'],
		highlights: ['Built from live sections', 'Short and skippable', 'Links into your first things'],
		screen: 'feed'
	},
	{
		key: 'live-demo',
		name: 'Live demo on the front page',
		emoji: '🪄',
		route: '/',
		tagline: 'Edit a real thing before you sign up.',
		description: 'The landing page embeds a live, editable thing tree with confetti, so the first thing you touch is the product itself.',
		category: 'core',
		audiences: ['founders', 'students', 'hobbyists'],
		highlights: ['Real tree, not a video', 'Add a thing, get confetti', 'No account needed'],
		screen: 'things'
	}
];

export const FEATURE_BY_KEY: Record<string, Feature> = byKey(FEATURES, (feature) => feature.key);

export const getFeature = (key: string): Feature => {
	const feature = FEATURE_BY_KEY[key];
	if (!feature) throw new Error(`Unknown marketing feature: ${key}`);
	return feature;
};

export const FEATURE_CATEGORY_LABELS: Record<Feature['category'], { name: string; emoji: string }> = {
	core: { name: 'Core', emoji: '🌳' },
	social: { name: 'Social', emoji: '📰' },
	builder: { name: 'Builder', emoji: '🧱' },
	developer: { name: 'Developers', emoji: '🔌' },
	ai: { name: 'AI', emoji: '🤖' },
	data: { name: 'Data', emoji: '💎' },
	account: { name: 'Account', emoji: '🔏' },
	apps: { name: 'Apps', emoji: '🧩' },
	design: { name: 'Design', emoji: '🎨' },
	mobile: { name: 'Everywhere', emoji: '📱' },
	admin: { name: 'Operations', emoji: '🛡️' }
};
