import { json } from '@vercel/remix';

import { fetchWeather, generateLopuMusing } from '~/api/utils/lopu/musing';

// GET /api/v1/lopu/musing — a little musing from Lopu, flavoured by the user's
// approximate location (Vercel geo headers) + current weather (Open-Meteo) +
// time of day. Generated by Claude when ANTHROPIC_API_KEY is set, else a
// canned fallback.
export const loader = async ({ request }: { request: Request }) => {
  const h = request.headers;
  const city = h.get('x-vercel-ip-city');
  const country = h.get('x-vercel-ip-country');
  const lat = h.get('x-vercel-ip-latitude');
  const lon = h.get('x-vercel-ip-longitude');

  const weather = lat && lon ? await fetchWeather(lat, lon) : null;
  const localTime = new Date().toLocaleTimeString('en-US', { hour: 'numeric', minute: '2-digit' });

  const result = await generateLopuMusing({
    city: city ? decodeURIComponent(city) : undefined,
    country: country || undefined,
    tempC: weather?.tempC,
    weather: weather?.weather,
    localTime
  });

  return json(result);
};
