import { consumeLopuMusingQuota } from '~/api/utils/lopu/rateLimit';
import { fetchWeather, hasLopuAiProviderConfigured, streamLopuMusing } from '~/api/utils/lopu/musing';

// Format the current time in the visitor's own timezone (Vercel geo header),
// falling back to UTC. Using the real timezone is what stops Lopu from saying
// "this afternoon" at midnight. en-US gives a clear "12:02 AM" so the AI knows
// the time of day unambiguously.
const formatLocalTime = (tz?: string | null): string => {
  try {
    return new Date().toLocaleTimeString('en-US', { hour: 'numeric', minute: '2-digit', timeZone: tz || 'UTC' });
  } catch {
    return new Date().toLocaleTimeString('en-US', { hour: 'numeric', minute: '2-digit' });
  }
};

// GET /api/v1/lopu/musing — a little musing from Lopu, flavoured by the user's
// approximate location (Vercel geo headers) + current weather (Open-Meteo) +
// local time of day. Streams the response as NDJSON (one JSON event per line):
//   {"type":"meta","source":"claude","mode":"weather"}
//   {"type":"delta","text":"The "}  ...  {"type":"done"}
// Generated by Claude/ChatGPT when a key is set, else a canned fallback.
export const loader = async ({ request }: { request: Request }) => {
  const h = request.headers;
  const city = h.get('x-vercel-ip-city');
  const country = h.get('x-vercel-ip-country');
  const lat = h.get('x-vercel-ip-latitude');
  const lon = h.get('x-vercel-ip-longitude');
  const tz = h.get('x-vercel-ip-timezone');
  const quota = hasLopuAiProviderConfigured() ? await consumeLopuMusingQuota(request) : null;
  const forceFallback = quota ? !quota.allowed : false;

  const weather = !forceFallback && lat && lon ? await fetchWeather(lat, lon) : null;

  const ctx = {
    city: city ? decodeURIComponent(city) : undefined,
    country: country || undefined,
    tempC: weather?.tempC,
    weather: weather?.weather,
    localTime: formatLocalTime(tz)
  };

  const encoder = new TextEncoder();
  const body = new ReadableStream({
    async start(controller) {
      try {
        for await (const ev of streamLopuMusing(ctx, { forceFallback })) {
          controller.enqueue(encoder.encode(JSON.stringify(ev) + '\n'));
        }
      } catch {
        controller.enqueue(encoder.encode(JSON.stringify({ type: 'delta', text: 'Lopu is daydreaming…' }) + '\n'));
        controller.enqueue(encoder.encode(JSON.stringify({ type: 'done' }) + '\n'));
      } finally {
        controller.close();
      }
    }
  });

  return new Response(body, {
    headers: {
      'Content-Type': 'application/x-ndjson; charset=utf-8',
      'Cache-Control': 'no-store',
      'X-Accel-Buffering': 'no',
      'X-Thingtime-Lopu-Rate-Limited': forceFallback ? 'true' : 'false',
      ...(quota ? { 'X-Thingtime-Lopu-RateLimit-Remaining': String(quota.remaining) } : {})
    }
  });
};
