// THINGMON rules — the pure game maths behind the Thingmon app suite
// (schemas/appSuites/thingmon.ts): eight elemental types and their chart,
// the move library, level-scaled stats, the damage / catch / flee formulas,
// experience and evolution. Everything is deterministic given the injected
// unit-interval generator, JSON-safe, and bounded (a battle turn touches two
// creatures and returns a handful of log lines).
//
// The species catalogue itself (60 original creatures + their pixel art) is
// generated by scripts/generate-thingmon-sprites.mjs into data/species.ts.

import { THINGMON_SPECIES_DATA } from './data/species';

export type ThingmonType = 'ember' | 'tide' | 'bloom' | 'spark' | 'frost' | 'stone' | 'shade' | 'glow';
export type Rarity = 'common' | 'uncommon' | 'rare' | 'legendary';
export type Rng = () => number;

export type Species = {
	id: number;
	slug: string;
	name: string;
	line: string;
	archetype: string;
	stage: number;
	types: ThingmonType[];
	rarity: Rarity;
	evolvesTo: { id: number; level: number } | null;
	evolvesFrom: number | null;
	habitats: string[];
	genus: string;
	flavor: string;
	baseStats: { hp: number; atk: number; def: number; spd: number };
	catchRate: number;
	baseExp: number;
	heightM: number;
	weightKg: number;
	sprite: string;
};

export const SPECIES: Species[] = (THINGMON_SPECIES_DATA as unknown as Species[]).map((entry) => ({ ...entry, types: [...entry.types] as ThingmonType[], habitats: [...entry.habitats] }));
const BY_ID = new Map(SPECIES.map((entry) => [entry.id, entry]));
const BY_SLUG = new Map(SPECIES.map((entry) => [entry.slug, entry]));
export const SPECIES_COUNT = SPECIES.length;

export const speciesById = (id: number): Species | undefined => BY_ID.get(id);
export const speciesBySlug = (slug: string): Species | undefined => BY_SLUG.get(slug.toLowerCase());
export const getSpecies = (idOrSlug: unknown): Species => {
	const found = typeof idOrSlug === 'number' ? speciesById(idOrSlug) : typeof idOrSlug === 'string' ? speciesBySlug(idOrSlug.trim()) || speciesById(Number(idOrSlug)) : undefined;
	if (!found) throw new Error(`No Thingmon species matches ${String(idOrSlug).slice(0, 40)}`);
	return found;
};

// ── types ───────────────────────────────────────────────────────────────────
export const TYPE_INFO: Record<ThingmonType, { emoji: string; color: string; ink: string; strong: ThingmonType[]; resist: ThingmonType[] }> = {
	ember: { emoji: '🔥', color: '#f0623a', ink: '#ffffff', strong: ['bloom', 'frost'], resist: ['tide', 'stone'] },
	tide: { emoji: '🌊', color: '#3f8fe0', ink: '#ffffff', strong: ['ember', 'stone'], resist: ['bloom', 'spark'] },
	bloom: { emoji: '🌿', color: '#5fb85a', ink: '#ffffff', strong: ['tide', 'stone'], resist: ['ember', 'frost'] },
	spark: { emoji: '⚡', color: '#f4c430', ink: '#3a2d00', strong: ['tide', 'glow'], resist: ['stone', 'shade'] },
	frost: { emoji: '❄️', color: '#9fd8f5', ink: '#1d3f5a', strong: ['bloom', 'spark'], resist: ['ember', 'stone'] },
	stone: { emoji: '🪨', color: '#9a8f82', ink: '#ffffff', strong: ['ember', 'frost', 'spark'], resist: ['tide', 'bloom'] },
	shade: { emoji: '🌙', color: '#5d4f8a', ink: '#ffffff', strong: ['glow', 'bloom'], resist: ['ember', 'spark'] },
	glow: { emoji: '✨', color: '#ffd86b', ink: '#3a2d00', strong: ['shade', 'frost'], resist: ['stone', 'tide'] }
};
export const TYPE_KEYS = Object.keys(TYPE_INFO) as ThingmonType[];

// attacker's move type against ONE defending type
export const typeMultiplier = (attack: ThingmonType, defend: ThingmonType): number => (TYPE_INFO[attack].strong.includes(defend) ? 2 : TYPE_INFO[attack].resist.includes(defend) ? 0.5 : 1);
export const effectiveness = (attack: ThingmonType, defending: ThingmonType[]): number => defending.reduce((total, type) => total * typeMultiplier(attack, type), 1);

// ── moves ───────────────────────────────────────────────────────────────────
export type StatusCondition = 'ok' | 'burned' | 'chilled' | 'shocked';
export type Move = { id: string; name: string; type: ThingmonType | 'neutral'; power: number; accuracy: number; level: number; effect?: { status?: StatusCondition; chance?: number; drain?: number }; flavor: string };

const move = (id: string, name: string, type: Move['type'], power: number, level: number, flavor: string, effect?: Move['effect'], accuracy = 100): Move => ({ id, name, type, power, accuracy, level, ...(effect ? { effect } : {}), flavor });

export const MOVES: Move[] = [
	move('bump', 'Bump', 'neutral', 35, 1, 'A hopeful shove.'),
	move('slam', 'Slam', 'neutral', 60, 12, 'The whole body, thrown.', undefined, 95),
	move('ember-flick', 'Ember Flick', 'ember', 40, 1, 'A flicked spark.'),
	move('flame-lash', 'Flame Lash', 'ember', 55, 8, 'A whip of fire.', { status: 'burned', chance: 0.15 }),
	move('blaze-rush', 'Blaze Rush', 'ember', 75, 16, 'A burning charge.', undefined, 95),
	move('inferno-bloom', 'Inferno Bloom', 'ember', 95, 26, 'A flower of flame opens.', { status: 'burned', chance: 0.25 }, 90),
	move('splash', 'Splash', 'tide', 40, 1, 'A cold slap of water.'),
	move('tide-whip', 'Tide Whip', 'tide', 55, 8, 'A lash of the tide.'),
	move('rip-current', 'Rip Current', 'tide', 75, 16, 'Drags the foe under.', undefined, 95),
	move('tsunami-coil', 'Tsunami Coil', 'tide', 95, 26, 'A wave that curls and crashes.', undefined, 90),
	move('leaf-nip', 'Leaf Nip', 'bloom', 40, 1, 'A quick bite of leaves.'),
	move('vine-snag', 'Vine Snag', 'bloom', 55, 8, 'Vines that drink a little of what they hold.', { drain: 0.3 }),
	move('thorn-volley', 'Thorn Volley', 'bloom', 75, 16, 'A hail of thorns.', undefined, 95),
	move('verdant-crush', 'Verdant Crush', 'bloom', 95, 26, 'The forest closes in.', { drain: 0.3 }, 90),
	move('static-zap', 'Static Zap', 'spark', 40, 1, 'A small, rude shock.', { status: 'shocked', chance: 0.1 }),
	move('volt-snap', 'Volt Snap', 'spark', 55, 8, 'A snap of voltage.'),
	move('arc-lance', 'Arc Lance', 'spark', 75, 16, 'A lance of lightning.', { status: 'shocked', chance: 0.2 }, 95),
	move('thunder-break', 'Thunder Break', 'spark', 95, 26, 'The sky breaks.', undefined, 90),
	move('snow-puff', 'Snow Puff', 'frost', 40, 1, 'A puff of snow.'),
	move('frost-bite', 'Frost Bite', 'frost', 55, 8, 'A bite that lingers cold.', { status: 'chilled', chance: 0.15 }),
	move('ice-shard', 'Ice Shard', 'frost', 75, 16, 'A hurled shard of ice.', undefined, 95),
	move('glacier-fall', 'Glacier Fall', 'frost', 95, 26, 'A glacier, dropped.', { status: 'chilled', chance: 0.25 }, 90),
	move('pebble-toss', 'Pebble Toss', 'stone', 40, 1, 'A tossed pebble.'),
	move('rock-butt', 'Rock Butt', 'stone', 55, 8, 'A headbutt with a rock for a head.'),
	move('boulder-roll', 'Boulder Roll', 'stone', 75, 16, 'Rolls right over the foe.', undefined, 90),
	move('quake-stomp', 'Quake Stomp', 'stone', 95, 26, 'The ground argues back.', undefined, 85),
	move('shadow-nip', 'Shadow Nip', 'shade', 40, 1, 'A nip from the dark.'),
	move('dusk-bite', 'Dusk Bite', 'shade', 55, 8, 'A bite at dusk.'),
	move('night-rend', 'Night Rend', 'shade', 75, 16, 'Tears at the light.', undefined, 95),
	move('void-howl', 'Void Howl', 'shade', 95, 26, 'A howl from nowhere.', undefined, 90),
	move('glimmer', 'Glimmer', 'glow', 40, 1, 'A dazzling glimmer.'),
	move('light-ray', 'Light Ray', 'glow', 55, 8, 'A ray of clean light.'),
	move('prism-beam', 'Prism Beam', 'glow', 75, 16, 'Every colour at once.', undefined, 95),
	move('nova-burst', 'Nova Burst', 'glow', 95, 26, 'A tiny star, briefly.', undefined, 90)
];
const MOVE_BY_ID = new Map(MOVES.map((entry) => [entry.id, entry]));
export const moveById = (id: string): Move | undefined => MOVE_BY_ID.get(id);
export const STRUGGLE: Move = move('struggle', 'Struggle', 'neutral', 30, 1, 'Nothing left but this.');

// the four newest moves a creature of these types knows at a level
export const movesFor = (types: ThingmonType[], level: number): Move[] => {
	const known = MOVES.filter((entry) => entry.level <= level && (entry.type === 'neutral' || types.includes(entry.type as ThingmonType)));
	return known.sort((a, b) => b.level - a.level || b.power - a.power).slice(0, 4).sort((a, b) => a.level - b.level || a.power - b.power);
};

// ── stats + creatures ───────────────────────────────────────────────────────
export const MAX_LEVEL = 50;
export const DEFAULT_IV = 8;
export const clampLevel = (level: number): number => Math.max(1, Math.min(MAX_LEVEL, Math.round(Number(level) || 1)));
// `typeof NaN === 'number'`, so a non-finite iv slips past a bare typeof test
// and turns every stat — and then hp, damage and the fainted check — into NaN:
// a battle that can neither be won nor lost. Every iv enters through here.
export const clampIv = (iv: unknown): number => (typeof iv === 'number' && Number.isFinite(iv) ? Math.max(0, Math.min(15, Math.round(iv))) : DEFAULT_IV);
// `Number(x) || fallback` already swallows NaN but keeps ±Infinity, and `??`
// only catches null/undefined — a stored NaN/Infinity needs both checks
const finite = (value: unknown, fallback: number): number => {
	const parsed = Number(value);
	return Number.isFinite(parsed) ? parsed : fallback;
};
export const calcStats = (species: Species, level: number, ivIn: number = DEFAULT_IV): { hp: number; atk: number; def: number; spd: number } => {
	const L = clampLevel(level);
	const iv = clampIv(ivIn);
	const stat = (base: number) => Math.floor(((2 * base + iv) * L) / 100) + 5;
	return { hp: Math.floor(((2 * species.baseStats.hp + iv) * L) / 100) + L + 10, atk: stat(species.baseStats.atk), def: stat(species.baseStats.def), spd: stat(species.baseStats.spd) };
};
export const expForLevel = (level: number): number => Math.pow(clampLevel(level), 3);
export const levelForExp = (exp: number): number => clampLevel(Math.floor(Math.cbrt(Math.max(0, Number(exp) || 0))));

export type Critter = {
	speciesId: number;
	species: string;
	nickname: string | null;
	types: ThingmonType[];
	rarity: Rarity;
	level: number;
	exp: number;
	iv: number;
	hp: number;
	maxHp: number;
	atk: number;
	def: number;
	spd: number;
	status: StatusCondition;
	moves: Array<{ id: string; name: string; type: string; power: number }>;
	sprite: string;
	stage: number;
};

export const newCritter = (spec: { speciesId: unknown; level?: unknown; nickname?: unknown; iv?: unknown }, rng: Rng): Critter => {
	const species = getSpecies(spec.speciesId);
	const level = clampLevel(Number(spec.level) || 5);
	const iv = typeof spec.iv === 'number' && Number.isFinite(spec.iv) ? clampIv(spec.iv) : Math.floor(rng() * 16);
	const stats = calcStats(species, level, iv);
	const nickname = typeof spec.nickname === 'string' && spec.nickname.trim() ? spec.nickname.trim().slice(0, 16) : null;
	return {
		speciesId: species.id,
		species: species.name,
		nickname,
		types: [...species.types],
		rarity: species.rarity,
		level,
		exp: expForLevel(level),
		iv,
		hp: stats.hp,
		maxHp: stats.hp,
		atk: stats.atk,
		def: stats.def,
		spd: stats.spd,
		status: 'ok',
		moves: movesFor(species.types, level).map((entry) => ({ id: entry.id, name: entry.name, type: entry.type, power: entry.power })),
		sprite: species.sprite,
		stage: species.stage
	};
};

// a stored member (anything the viewer's data thing holds) → a well-formed critter
export const normalizeCritter = (value: unknown, label: string): Critter => {
	if (!value || typeof value !== 'object' || Array.isArray(value)) throw new Error(`${label} must be a creature record`);
	const raw = value as Record<string, unknown>;
	const species = getSpecies(raw.speciesId);
	const level = clampLevel(Number(raw.level) || 1);
	const iv = clampIv(raw.iv);
	const stats = calcStats(species, level, iv);
	const maxHp = stats.hp;
	const hp = Math.max(0, Math.min(maxHp, Math.round(finite(raw.hp ?? maxHp, maxHp))));
	const status = (['ok', 'burned', 'chilled', 'shocked'] as StatusCondition[]).includes(raw.status as StatusCondition) ? (raw.status as StatusCondition) : 'ok';
	const knownMoves = Array.isArray(raw.moves) ? raw.moves.map((entry) => (entry && typeof entry === 'object' ? (entry as { id?: unknown }).id : entry)).filter((id): id is string => typeof id === 'string' && MOVE_BY_ID.has(id)) : [];
	const moves = (knownMoves.length ? knownMoves.map((id) => MOVE_BY_ID.get(id)!) : movesFor(species.types, level)).slice(0, 4);
	return {
		speciesId: species.id,
		species: species.name,
		nickname: typeof raw.nickname === 'string' && raw.nickname.trim() ? raw.nickname.trim().slice(0, 16) : null,
		types: [...species.types],
		rarity: species.rarity,
		level,
		exp: Math.max(expForLevel(level), Math.min(expForLevel(MAX_LEVEL), Math.round(finite(raw.exp, 0)))),
		iv,
		hp,
		maxHp,
		atk: stats.atk,
		def: stats.def,
		spd: stats.spd,
		status,
		moves: moves.map((entry) => ({ id: entry.id, name: entry.name, type: entry.type, power: entry.power })),
		sprite: species.sprite,
		stage: species.stage
	};
};
export const displayName = (critter: Pick<Critter, 'nickname' | 'species'>): string => critter.nickname || critter.species;

// ── battle ──────────────────────────────────────────────────────────────────
export type Strike = { damage: number; effectiveness: number; crit: boolean; missed: boolean; status: StatusCondition | null; drained: number };

export const effectiveSpeed = (critter: Critter): number => (critter.status === 'chilled' ? Math.floor(critter.spd / 2) : critter.spd);

export const strike = (attacker: Critter, defender: Critter, moveSpec: Move, rng: Rng): Strike => {
	if (rng() * 100 >= moveSpec.accuracy) return { damage: 0, effectiveness: 1, crit: false, missed: true, status: null, drained: 0 };
	const stab = moveSpec.type !== 'neutral' && attacker.types.includes(moveSpec.type) ? 1.5 : 1;
	const eff = moveSpec.type === 'neutral' ? 1 : effectiveness(moveSpec.type, defender.types);
	const crit = rng() < 1 / 16;
	const atk = attacker.status === 'burned' ? Math.floor(attacker.atk * 0.75) : attacker.atk;
	const base = Math.floor((((2 * attacker.level) / 5 + 2) * moveSpec.power * atk) / Math.max(1, defender.def) / 50) + 2;
	const roll = 0.85 + rng() * 0.15;
	const damage = Math.max(1, Math.floor(base * stab * eff * (crit ? 1.5 : 1) * roll));
	const applied = Math.min(defender.hp, damage);
	const status = moveSpec.effect?.status && defender.status === 'ok' && rng() < (moveSpec.effect.chance ?? 0) ? moveSpec.effect.status : null;
	const drained = moveSpec.effect?.drain ? Math.max(1, Math.floor(applied * moveSpec.effect.drain)) : 0;
	return { damage: applied, effectiveness: eff, crit, missed: false, status, drained };
};

const effLine = (eff: number): string => (eff >= 2 ? ' It’s super effective!' : eff < 1 ? ' It’s not very effective…' : '');

export type TurnOutcome = 'continue' | 'won' | 'fainted';
export type Turn = { player: Critter; wild: Critter; log: string[]; outcome: TurnOutcome };

const act = (attacker: Critter, defender: Critter, moveSpec: Move, rng: Rng, log: string[]): { attacker: Critter; defender: Critter } => {
	const who = displayName(attacker);
	if (attacker.status === 'shocked' && rng() < 0.25) {
		log.push(`${who} is shocked and can’t move!`);
		return { attacker, defender };
	}
	const result = strike(attacker, defender, moveSpec, rng);
	if (result.missed) {
		log.push(`${who} used ${moveSpec.name}… it missed!`);
		return { attacker, defender };
	}
	let line = `${who} used ${moveSpec.name}!${result.crit ? ' A critical hit!' : ''}${effLine(result.effectiveness)}`;
	const nextDefender: Critter = { ...defender, hp: Math.max(0, defender.hp - result.damage), status: result.status ?? defender.status };
	if (result.status) line += ` ${displayName(defender)} is ${result.status}!`;
	let nextAttacker = attacker;
	if (result.drained) {
		nextAttacker = { ...attacker, hp: Math.min(attacker.maxHp, attacker.hp + result.drained) };
		line += ` ${who} drank ${result.drained} HP.`;
	}
	log.push(line);
	return { attacker: nextAttacker, defender: nextDefender };
};

const endOfTurn = (critter: Critter, log: string[]): Critter => {
	if (critter.status === 'burned' && critter.hp > 0) {
		const chip = Math.max(1, Math.floor(critter.maxHp / 16));
		log.push(`${displayName(critter)} is hurt by its burn.`);
		return { ...critter, hp: Math.max(0, critter.hp - chip) };
	}
	return critter;
};

export const wildMove = (wild: Critter, rng: Rng): Move => {
	const known = wild.moves.map((entry) => MOVE_BY_ID.get(entry.id)).filter((entry): entry is Move => !!entry);
	return known.length ? known[Math.floor(rng() * known.length)] : STRUGGLE;
};

// one full turn: the player's chosen move and the wild's reply, in speed order
export const resolveTurn = (playerIn: Critter, wildIn: Critter, moveIndex: number, rng: Rng): Turn => {
	const log: string[] = [];
	const index = Math.max(0, Math.min(playerIn.moves.length - 1, Math.round(Number(moveIndex) || 0)));
	const playerMove = MOVE_BY_ID.get(playerIn.moves[index]?.id || '') || STRUGGLE;
	const wildChoice = wildMove(wildIn, rng);
	let player = playerIn;
	let wild = wildIn;
	const playerFirst = effectiveSpeed(player) > effectiveSpeed(wild) || (effectiveSpeed(player) === effectiveSpeed(wild) && rng() < 0.5);
	const order: Array<'player' | 'wild'> = playerFirst ? ['player', 'wild'] : ['wild', 'player'];
	for (const side of order) {
		if (player.hp <= 0 || wild.hp <= 0) break;
		if (side === 'player') {
			const result = act(player, wild, playerMove, rng, log);
			player = result.attacker;
			wild = result.defender;
		} else {
			const result = act(wild, player, wildChoice, rng, log);
			wild = result.attacker;
			player = result.defender;
		}
	}
	if (player.hp > 0 && wild.hp > 0) {
		player = endOfTurn(player, log);
		wild = endOfTurn(wild, log);
	}
	const outcome: TurnOutcome = wild.hp <= 0 ? 'won' : player.hp <= 0 ? 'fainted' : 'continue';
	if (outcome === 'won') log.push(`The wild ${wild.species} fainted!`);
	if (outcome === 'fainted') log.push(`${displayName(player)} fainted!`);
	return { player, wild, log, outcome };
};

// the wild acts alone (after a failed catch or flee)
export const wildReply = (playerIn: Critter, wildIn: Critter, rng: Rng, log: string[]): Turn => {
	const result = act(wildIn, playerIn, wildMove(wildIn, rng), rng, log);
	let player = result.defender;
	let wild = result.attacker;
	if (player.hp > 0) {
		player = endOfTurn(player, log);
		wild = endOfTurn(wild, log);
	}
	const outcome: TurnOutcome = player.hp <= 0 ? 'fainted' : 'continue';
	if (outcome === 'fainted') log.push(`${displayName(player)} fainted!`);
	return { player, wild, log, outcome };
};

// ── items + catching ────────────────────────────────────────────────────────
export type Item = { id: string; name: string; emoji: string; kind: 'crystal' | 'heal'; price: number; bonus?: number; heal?: number; cures?: boolean; blurb: string };
export const ITEMS: Item[] = [
	{ id: 'shard-crystal', name: 'Shard crystal', emoji: '🔹', kind: 'crystal', price: 12, bonus: 1, blurb: 'A rough capture crystal. Works best on tired, small things.' },
	{ id: 'tide-crystal', name: 'Tide crystal', emoji: '🔷', kind: 'crystal', price: 30, bonus: 1.5, blurb: 'A polished crystal with better odds.' },
	{ id: 'prism-crystal', name: 'Prism crystal', emoji: '💠', kind: 'crystal', price: 80, bonus: 2.5, blurb: 'A flawless prism. The rare ones notice it.' },
	{ id: 'tonic', name: 'Tonic', emoji: '🧪', kind: 'heal', price: 15, heal: 30, blurb: 'Restores 30 HP.' },
	{ id: 'elixir', name: 'Elixir', emoji: '🍵', kind: 'heal', price: 45, heal: 9999, cures: true, blurb: 'Full heal and cures every condition.' }
];
const ITEM_BY_ID = new Map(ITEMS.map((entry) => [entry.id, entry]));
export const itemById = (id: unknown): Item => {
	const found = typeof id === 'string' ? ITEM_BY_ID.get(id) : undefined;
	if (!found) throw new Error(`No such item: ${String(id).slice(0, 30)}`);
	return found;
};
export const STARTER_BAG: Record<string, number> = { 'shard-crystal': 5, tonic: 2 };
export const STARTER_SHARDS = 20;

export const catchChance = (wild: Critter, item: Item): number => {
	const species = getSpecies(wild.speciesId);
	const hpFactor = (3 * wild.maxHp - 2 * wild.hp) / (3 * wild.maxHp);
	const statusBonus = wild.status === 'ok' ? 1 : 1.5;
	return Math.min(1, ((species.catchRate * hpFactor * (item.bonus ?? 1) * statusBonus) / 255) * 1.1);
};
export const catchRoll = (wild: Critter, item: Item, rng: Rng): { caught: boolean; shakes: number; chance: number } => {
	if (item.kind !== 'crystal') throw new Error(`${item.name} is not a capture crystal`);
	const chance = catchChance(wild, item);
	const perShake = Math.pow(chance, 1 / 3);
	let shakes = 0;
	for (let i = 0; i < 3; i++) {
		if (rng() < perShake) shakes += 1;
		else break;
	}
	return { caught: shakes === 3, shakes, chance: Number(chance.toFixed(3)) };
};
export const SHAKE_LINES = ['It broke free right away!', 'It wobbled once… and broke free.', 'It wobbled twice… so close!', 'Gotcha!'];

export const fleeRoll = (player: Critter, wild: Critter, attempts: number, rng: Rng): { escaped: boolean; odds: number } => {
	const odds = Math.min(1, (Math.floor((effectiveSpeed(player) * 128) / Math.max(1, effectiveSpeed(wild))) + 30 * Math.max(0, attempts)) / 256);
	return { escaped: rng() < odds, odds: Number(odds.toFixed(2)) };
};

export const applyItem = (critter: Critter, item: Item, inBattle = false): { critter: Critter; message: string; consumed: boolean } => {
	if (item.kind !== 'heal') throw new Error(`${item.name} can only be thrown at a wild Thingmon`);
	if (critter.hp <= 0 && !inBattle) return { critter, message: `${displayName(critter)} has fainted — rest at the sanctuary first.`, consumed: false };
	const healed = Math.min(critter.maxHp, critter.hp + (item.heal ?? 0));
	const cured = item.cures && critter.status !== 'ok';
	if (healed === critter.hp && !cured) return { critter, message: `${displayName(critter)} is already in fine shape.`, consumed: false };
	return { critter: { ...critter, hp: healed, status: item.cures ? 'ok' : critter.status }, message: `${displayName(critter)} recovered ${healed - critter.hp} HP${cured ? ' and feels fine again' : ''}.`, consumed: true };
};
export const healFully = (critter: Critter): Critter => ({ ...critter, hp: critter.maxHp, status: 'ok' });

// ── experience + evolution ──────────────────────────────────────────────────
export const expGainFor = (defeated: Pick<Critter, 'speciesId' | 'level'>): number => Math.max(1, Math.floor((getSpecies(defeated.speciesId).baseExp * defeated.level) / 7));
export const shardsFor = (defeated: Pick<Critter, 'level' | 'rarity'>): number => 4 + defeated.level * 2 + (defeated.rarity === 'rare' ? 20 : defeated.rarity === 'legendary' ? 100 : 0);

export const grantExp = (critter: Critter, amount: number): { critter: Critter; from: number; to: number; leveledUp: boolean } => {
	const exp = Math.min(expForLevel(MAX_LEVEL), critter.exp + Math.max(0, Math.round(finite(amount, 0))));
	const to = levelForExp(exp);
	const from = critter.level;
	if (to <= from) return { critter: { ...critter, exp }, from, to: from, leveledUp: false };
	const species = getSpecies(critter.speciesId);
	const stats = calcStats(species, to, critter.iv);
	const hpGain = stats.hp - critter.maxHp;
	return {
		critter: { ...critter, exp, level: to, maxHp: stats.hp, hp: Math.min(stats.hp, critter.hp + hpGain), atk: stats.atk, def: stats.def, spd: stats.spd, moves: movesFor(critter.types, to).map((entry) => ({ id: entry.id, name: entry.name, type: entry.type, power: entry.power })) },
		from,
		to,
		leveledUp: true
	};
};

export const canEvolve = (critter: Pick<Critter, 'speciesId' | 'level'>): Species | null => {
	const species = getSpecies(critter.speciesId);
	if (!species.evolvesTo || critter.level < species.evolvesTo.level) return null;
	return speciesById(species.evolvesTo.id) || null;
};
export const evolve = (critter: Critter): { critter: Critter; from: string; to: string } => {
	const next = canEvolve(critter);
	if (!next) throw new Error(`${displayName(critter)} is not ready to evolve`);
	const stats = calcStats(next, critter.level, critter.iv);
	const hpRatio = critter.maxHp ? critter.hp / critter.maxHp : 1;
	return {
		critter: {
			...critter,
			speciesId: next.id,
			species: next.name,
			types: [...next.types],
			rarity: next.rarity,
			maxHp: stats.hp,
			hp: Math.max(1, Math.round(stats.hp * hpRatio)),
			atk: stats.atk,
			def: stats.def,
			spd: stats.spd,
			moves: movesFor(next.types, critter.level).map((entry) => ({ id: entry.id, name: entry.name, type: entry.type, power: entry.power })),
			sprite: next.sprite,
			stage: next.stage
		},
		from: critter.species,
		to: next.name
	};
};

// ── zones + encounters ──────────────────────────────────────────────────────
export type Zone = { id: string; name: string; emoji: string; blurb: string; levels: [number, number]; unlockDex: number; color: string };
export const ZONES: Zone[] = [
	{ id: 'meadow', name: 'Meadow', emoji: '🌾', blurb: 'Tall grass, warm sun, easy company.', levels: [2, 7], unlockDex: 0, color: '#e6f6d5' },
	{ id: 'tidepool', name: 'Tidepools', emoji: '🐚', blurb: 'Rock pools that hum when the tide turns.', levels: [4, 10], unlockDex: 0, color: '#dff1ff' },
	{ id: 'embercave', name: 'Ember Caves', emoji: '🕳️', blurb: 'Warm tunnels lit from below.', levels: [8, 16], unlockDex: 3, color: '#ffe3d6' },
	{ id: 'duskmarsh', name: 'Dusk Marsh', emoji: '🌫️', blurb: 'Reeds, fog, and things that watch.', levels: [10, 20], unlockDex: 6, color: '#e6e0f5' },
	{ id: 'frostpeak', name: 'Frost Peak', emoji: '🏔️', blurb: 'Thin air, thick snow, old ice.', levels: [12, 22], unlockDex: 9, color: '#eaf6ff' },
	{ id: 'skybluff', name: 'Sky Bluff', emoji: '🪁', blurb: 'The cliffs where the wind lives.', levels: [15, 28], unlockDex: 12, color: '#fff6d6' }
];
export const zoneById = (id: unknown): Zone => {
	const found = typeof id === 'string' ? ZONES.find((zone) => zone.id === id) : undefined;
	if (!found) throw new Error(`No such zone: ${String(id).slice(0, 30)}`);
	return found;
};
export const LEGENDARY_DEX_THRESHOLD = 18;
const RARITY_WEIGHT: Record<Rarity, number> = { common: 60, uncommon: 25, rare: 12, legendary: 1 };

export const rollEncounter = (zoneId: unknown, dexCaught: number, rng: Rng): Critter => {
	const zone = zoneById(zoneId);
	const legendaryOk = dexCaught >= LEGENDARY_DEX_THRESHOLD;
	const pool = SPECIES.filter((species) => species.habitats.includes(zone.id) && (species.rarity !== 'legendary' || legendaryOk));
	if (!pool.length) throw new Error(`Nothing lives in ${zone.name}`);
	const total = pool.reduce((sum, species) => sum + RARITY_WEIGHT[species.rarity], 0);
	let pick = rng() * total;
	let chosen = pool[pool.length - 1];
	for (const species of pool) {
		pick -= RARITY_WEIGHT[species.rarity];
		if (pick <= 0) {
			chosen = species;
			break;
		}
	}
	const [lo, hi] = zone.levels;
	const level = chosen.rarity === 'legendary' ? hi + 5 : lo + Math.floor(rng() * (hi - lo + 1));
	return newCritter({ speciesId: chosen.id, level }, rng);
};
export const STARTER_IDS = [1, 4, 7];
