// 🦄 Lopu's fallback musings — a big hand-written library so the musing API is
// ALWAYS live and delightful, even with no API keys set or when Claude/OpenAI
// credits are exhausted. These are Lopu's voice: warm, a touch magical, short,
// at most one emoji. Rotated by time in musing.ts (no RNG — CodeQL-friendly).

// 🔮 The make-a-wish slots (claude-todo/10): at 11:11 and midnight the musing
// endpoint swaps in these instead of the rotation. Keyed off the SAME
// visitor-timezone string the musing prompt uses (formatLocalTime's en-US
// "h:mm AM/PM" shape), so seeded calls and real visitors hit the same slots —
// deterministic, zero RNG, zero UI work.
const WISH_MUSING = "It's 11:11 — close your eyes and make a wish. 🌠 (Lopu already made one for you.)";
const MIDNIGHT_MUSING = 'Midnight exactly — a brand-new day, still unwritten. Wish well. 🌠';

export const wishSlotMusing = (localTime: string): string | null => {
	if (localTime === '11:11 AM' || localTime === '11:11 PM') return WISH_MUSING;
	if (localTime === '12:00 AM') return MIDNIGHT_MUSING;
	return null;
};

// The one shared picker: time-rotated, RNG-free (CodeQL-friendly), same slot
// for everyone in the same instant — deterministic in the test==live sense.
// Used by the musing stream and the waitlist welcome fortune.
export const pickFallbackMusing = (): string => FALLBACK_MUSINGS[Date.now() % FALLBACK_MUSINGS.length];

export const FALLBACK_MUSINGS: string[] = [
  'Tiny things become big things. Keep tending the little ones. ✨',
  'The best ideas, like unicorns, show up when you stop chasing them. 🦄',
  'Somewhere a rainbow is forming just because you showed up today. 🌈',
  'You are allowed to make something just because it delights you. 🎈',
  "Progress hides in the boring parts — you're closer than it feels. 🌱",
  'Begin badly. Beginning badly is still beginning. 🌟',
  'The smallest step counts double on a slow day. 🐌',
  'Your future self is quietly cheering for what you do right now. 📣',
  'Curiosity is a compass that never needs charging. 🧭',
  'Rest is not the opposite of progress; it is part of it. 🛌',
  'A messy first draft is a brave first draft. 🖋️',
  'You can do hard things in soft, gentle ways. 🌸',
  'Wonder is just attention wearing its party hat. 🎉',
  'Plant the idea today; you do not have to harvest it yet. 🌾',
  'Even rivers take the scenic route to the sea. 🏞️',
  'Be patient with the chapter you are still writing. 📖',
  'Small sparks are how every wildfire of joy begins. 🔥',
  'You do not need permission to be a little bit magical. 🪄',
  'The door you are looking for might just need a gentle push. 🚪',
  'Today is a blank page and you hold the glitter pen. ✒️',
  'Trust the slow bloom; some flowers open at their own hour. 🌷',
  'Your weird, specific idea is exactly the one worth keeping. 🦄',
  'Kindness to yourself is a productivity hack nobody mentions. 💗',
  'The stars do not compete; they simply shine where they are. ⭐',
  'A tiny win before lunch can color the whole afternoon. 🍋',
  'Let your curiosity off the leash for ten whole minutes. 🐾',
  'Some days the bravest thing is to simply continue. 🧗',
  'You are made of stardust and stubbornness, a great combination. ✨',
  'The fog always lifts; it just forgets to announce when. 🌫️',
  'Make it, then make it better. In that order, always. 🛠️',
  'A single good question can outshine a hundred answers. ❓',
  'Your enthusiasm is contagious; go spread a little of it. 🌟',
  'Even the moon takes nights off to be a sliver. 🌙',
  'Done is a kind of magic; perfect is a kind of trap. 🪤',
  'Notice one beautiful thing today and let it stay a while. 🌼',
  'You are exactly one good idea away from a great day. 💡',
  'Small consistent magic beats one giant burst of it. 🔮',
  'The path appears as you walk it, never a moment before. 🚶',
  'Let today be gentle and a little bit golden. 🌅',
  'Your imagination has no fuel gauge; it never runs empty. ⛽',
  'Brave is just scared with its sleeves rolled up. 💪',
  'A nap and a snack have solved more problems than panic ever has. 🍪',
  'You are growing even on the days it feels like standing still. 🌳',
  'Follow the thread of what makes you curious; it knows things. 🧵',
  'Some seeds you planted long ago are sprouting right now. 🌱',
  'The kindest critic and the boldest dreamer can be the same person. 💞',
  'Make room for play; that is where the good ideas nest. 🪺',
  'Your pace is the right pace because it is yours. 🐢',
  'A little awe a day keeps the grayness away. 🌈',
  'You do not have to feel ready to begin being ready. 🚀',
  'Collect tiny joys like a magpie collects shiny things. 🐦',
  'The universe loves a try; it rewards even the wobbly ones. 🎯',
  'Soften your shoulders; the mountain is patient with you. ⛰️',
  'Today, be the friendly weather in someone else’s sky. ☀️',
  'Half-finished is just full-of-potential in disguise. 🧩',
  'You carry your own little lighthouse; let it sweep the dark. 🗼',
  'Pay attention to what hums; that hum is your direction. 🎶',
  'A small kindness is never wasted, never too late. 💌',
  'Let yourself be a beginner; beginners get the best surprises. 🎁',
  'The whole sky fits in one upward glance. Go look. 🌌',
  'Your work matters even on the days no one is watching. 👀',
  'Wonder is free and refillable; help yourself to seconds. 🍮',
  'Trust the version of you that started this. 🌟',
  'Slow mornings make for steady afternoons. ☕',
  'You are allowed to change your mind and still be consistent. 🔄',
  'Every expert was once a delighted, clueless beginner. 🐣',
  'Plant patience; harvest peace. 🌾',
  'The smallest candle still wins against the biggest dark. 🕯️',
  'Let curiosity, not pressure, set today’s pace. 🧭',
  'A good idea whispered counts as much as one shouted. 🤫',
  'You are the plot twist your story has been waiting for. 📚',
  'Give the day a chance to surprise you. 🎲',
  'Build the thing for the joy of building; the rest follows. 🧱',
  'Even storms are just the sky doing some big feelings. ⛈️',
  'Be soft with the parts of you that are still learning. 🫧',
  'A walk solves what a worry only multiplies. 🚶‍♀️',
  'Your potential is not a deadline; it is a horizon. 🌅',
  'Make one corner of your world a little brighter today. 💫',
  'The right time is usually a slightly braver version of now. ⏳',
  'Let yourself daydream; that is research for the soul. 💭',
  'You bloom in seasons, not in a single afternoon. 🌻',
  'A tidy desk and a wild idea make a great team. 🗂️',
  'Keep the spark; the fire will figure itself out. 🔥',
  'You are doing better than the harsh voice claims. 🕊️',
  'Treat your ideas like guests: feed them, give them room. 🍽️',
  'Small loops of practice spin into big wheels of skill. ⚙️',
  'The sea is patient; be a little sea about it. 🌊',
  'Look up more often; the clouds are putting on a show. ☁️',
  'You can always start a kinder day at any hour. 🌗',
  'Joy counts as a result, not just a reward. 🎈',
  'Let the small good thing be enough for today. 🌿',
  'Your weirdness is a feature; never patch it out. 🦄',
  'Momentum is shy; coax it with one tiny task. 🪶',
  'The garden does not rush, and look how it turns out. 🌷',
  'Be the calm you would want to borrow on a hard day. 🧘',
  'A question kept alive is worth more than a fact stored away. 💭',
  'You were made for more than just getting through the day. ✨',
  'Tend your attention; it is the most magical thing you own. 🪄',
  'Some days you carry the light; some days you follow it. 🔦',
  'Make peace with the draft and the draft makes peace with you. 📝',
  'A little wonder rewires a whole gray afternoon. 🌈',
  'You are not behind; you are simply on your own clock. ⏰',
  'Cheer for your small wins as loudly as the big ones. 🎊',
  'The kind word you give yourself echoes the longest. 💗',
  'Let today be a gentle experiment with no wrong answers. 🧪',
  'Even the longest night is just practice for dawn. 🌄',
  'Your enthusiasm is renewable; plug it back in often. 🔌',
  'A small detour can be the scenic part of the story. 🛤️',
  'Hold your plans lightly and your wonder tightly. 🎈',
  'You are allowed to take up a little more space today. 🌍',
  'Make the thing imperfectly; perfection never ships. 🚢',
  'A grateful glance turns the ordinary slightly golden. 🌟',
  'Be curious about the obstacle; it may be a doorway. 🚪',
  'You can rest without quitting; they are different doors. 🛋️',
  'Tiny rituals are little anchors on a windy day. ⚓',
  'Let the good idea simmer; rushing scorches it. 🍲',
  'You have survived every hard day so far; that is data. 📊',
  'Wonder is the quiet rebellion against a dull day. 🌠',
  'Pick the kinder interpretation; it is usually truer anyway. 🕊️',
  'The world needs your particular flavor of magic. 🍦',
  'A short list beats a long worry every time. ✅',
  'You are the gardener and the garden both. 🌱',
  'Let yourself be amazed; it costs nothing and pays in glow. ✨',
  'Steady beats flashy over a long enough road. 🛣️',
  'Your softness is not weakness; it is a kind of strength. 🌸',
  'One brave sentence can unstick a whole stuck day. 🖋️',
  'The little spark you are protecting is worth protecting. 🔥',
  'Be generous with your curiosity and stingy with your doubt. 🧲',
  'A new day is a clean canvas; you brought the colors. 🎨',
  'Let the quiet moments count as much as the loud wins. 🤍',
  'You are allowed to enjoy the part you are good at. 🏅',
  'Hope is a muscle; it grows the more gently you use it. 💪',
  'The path of least sparkle is rarely the one to take. ✨',
  'Make today one percent more wonderful than yesterday. 📈',
  'A small, true thing outshines a big, fake one. 💎',
  'You do not have to bloom on schedule to be a flower. 🌼',
  'Curiosity turns chores into tiny quests. 🗺️',
  'Be patient; even comets only come around when ready. ☄️',
  'Your gentle effort today is a gift to tomorrow’s you. 🎁',
  'Let wonder be the first thing you reach for. 🌅',
  'A little bit done daily beats a lot done never. 🗓️',
  'You can hold both the doubt and the dream; just keep walking. 🚶',
  'Some magic only shows up after the third try. 🪄',
  'Be the reason someone’s ordinary day got a sparkle. 💫',
  'The smallest yes to yourself can change a whole week. 🌟',
  'Let your ideas be playful; play is where they get clever. 🎠',
  'A calm breath is a tiny reset button you always carry. 🫁',
  'You are a work in progress, and the progress is the point. 🛠️',
  'Notice the good; it is shy and easily overlooked. 🐾',
  'Even the slowest cloud eventually crosses the whole sky. ☁️',
  'Make space for delight; it rarely barges in uninvited. 🚪',
  'Your story is still being written, and you hold the pen. ✒️',
  'A single kind thought, aimed inward, can change the day. 💗',
  'Let today be lighter than yesterday by just one feather. 🪶',
  'The wonder you give away always grows back larger. 🌈',
  'You are braver in motion than you ever feel at the start. 🏃',
  'Tend the spark and let the bonfire be future-you’s problem. 🔥',
  'A gentle plan beats a frantic one nine times out of ten. 🗒️',
  'Small magic, often repeated, becomes a kind of superpower. ⚡',
  'You can always begin again, as many times as it takes. 🔄',
  'Let the morning light reset whatever yesterday tangled. 🌅',
  'Your quiet effort is a kind of glow that others feel. 💡',
  'Be amazed at something small before noon; it sets the tone. 🌼',
  'The bravest art is the one you almost did not make. 🎨',
  'A soft start still gets you out the door. 🚪',
  'You are allowed to grow in the direction that delights you. 🌻',
  'Wonder first, worry later — if at all. 🌠',
  'Tiny improvements compound into quiet miracles. ✨',
  'Hold the dream loosely enough that it can grow. 🎈',
  'You are someone’s favorite kind of magic. 🦄',
  'Let curiosity win the argument with comfort, just this once. 🧭',
  'A little chaos is just creativity stretching its legs. 🌀',
  'The good idea is patient; it will wait for your courage. ⏳',
  'You can be tired and still be on your way. 🚶',
  'Make peace with slow; slow still arrives. 🐢',
  'Your attention is a spotlight; aim it at something lovely. 🔦',
  'Let the small joy be loud enough to hear. 🔔',
  'Even half a step keeps the door of momentum open. 🚪',
  'You are not too late for the things meant for you. ⏰',
  'A gentle why can unlock a stubborn how. 🗝️',
  'Today, give your ideas room to be a little ridiculous. 🤹',
  'The light you are looking for is partly the one you carry. 🕯️',
  'Be soft, be curious, be slightly unstoppable. 🌈',
  'A tiny act of courage rewires a timid afternoon. 💪',
  'You can polish later; right now, just make it exist. 🪙',
  'Let wonder lead and let worry follow at a distance. 🌟',
  'Your potential is not measured by your fastest day. 🐌',
  'Plant kindness; it grows in every season. 🌷',
  'A curious mind is never truly lost, only exploring. 🧭',
  'You brought something to today that no one else could. 🎁',
  'Let the small spark count as a real beginning. 🔥',
  'Some of your best work will start as a doodle. ✏️',
  'Be the warm light at the edge of someone’s hard day. 🌅',
  'A short rest is a long-term strategy. 🛌',
  'Your gentleness is a quiet kind of bravery. 🕊️',
  'Make the leap a little smaller and take it anyway. 🐸',
  'Wonder is the cheapest, finest fuel there is. ⛽',
  'You are allowed to be proud of small, real progress. 🏅',
  'The fog of a hard morning is not the shape of the day. 🌫️',
  'A single curious step beats a hundred anxious ones. 👣',
  'Let your ideas play together; that is how they pair up. 🤝',
  'You are closer to the breakthrough than to the beginning. 📈',
  'Tend today gently and tomorrow tends itself a little. 🌱',
  'A bright thought, written down, stops being a daydream. 📝',
  'You can carry hope in your pocket like a smooth stone. 🪨',
  'Let the wins be small and frequent; they add up loud. 🎊',
  'The world is more magic than it lets on; go double-check. 🔍',
  'Be patient with the seedling that is you. 🌱',
  'A calm heart makes a clear map. 🗺️',
  'You do not have to earn rest; it is part of the work. 🛋️',
  'Let your curiosity outvote your fear today. 🗳️',
  'Even a flicker is enough to find the next match. 🕯️',
  'You are allowed to want good things gently and fiercely. 💞',
  'Make room for the idea that has been knocking. 🚪',
  'A slow yes to yourself is still a yes. 🌟',
  'The smallest delight, fully noticed, is a tiny vacation. 🏝️',
  'You are growing roots on the days you feel stuck. 🌳',
  'Let wonder be your default setting today. ✨',
  'A kind inner voice gets more done than a cruel one. 💗',
  'Begin where you are; that is the only door available. 🚪',
  'Your ordinary day holds at least one quiet marvel. 🌼',
  'Be brave in small, repeatable ways. 🔁',
  'The dream does not need to be loud to be real. 🤍',
  'Let curiosity carry the heavy parts for a while. 🧳',
  'You can be the sunny break in your own forecast. ☀️',
  'A tiny ritual can hold a whole day steady. ⚓',
  'Some doors only open to a gentle, patient knock. ✊',
  'You are allowed to do the next small right thing. ✅',
  'Wonder turns waiting into watching. 👀',
  'Let the kind thought arrive first tomorrow. 🌅',
  'A short, true effort beats a long, fake one. ⏱️',
  'You are made for more wonder than you usually allow. 🌌',
  'Tend the little spark; protect it from the wind of doubt. 🔥',
  'Be patient; the best chapters take a few drafts. 📖',
  'A bit of play unsticks the most serious problem. 🎲',
  'You can rest your hands without resting your hope. 🤲',
  'Let today be a soft landing for a tired idea. 🪂',
  'The smallest brave act echoes farther than you think. 📣',
  'You are someone’s good weather; carry that lightly. ☀️',
  'A new angle is sometimes all the magic you need. 📐',
  'Let curiosity be louder than comparison today. 🔊',
  'You are allowed to bloom slowly and beautifully. 🌸',
  'Tiny sparks are how all the good fires start. ✨',
  'Be gentle; even mountains were shaped by patient water. 🏔️',
  'A short walk and a long breath fix a surprising amount. 🚶',
  'You can hold the dream and the doubt and still move. 🎈',
  'Let the small good moment be the whole point sometimes. 🌿',
  'Your effort today is a love letter to your future self. 💌',
  'Wonder is the quietest, strongest kind of yes. 🌟',
  'Be curious enough to surprise yourself this week. 🎁',
  'A soft start is still a start, and starts are everything. 🌅',
  'You are allowed to enjoy the climb, not just the view. ⛰️',
  'Tend your curiosity like a small, glowing pet. 🐾',
  'The day improves the moment you decide to notice the good. 🌈',
  'Let your ideas be brave on your behalf. 🦁',
  'A tiny bit of magic, on purpose, changes everything. 🪄',
  'You are not stuck; you are gathering momentum quietly. 🌀',
  'Be the calm that the busy day was missing. 🧘',
  'A single small joy can hold up a whole afternoon. 🎈',
  'Let the gentle plan win over the frantic one. 🗒️',
  'You carry more light than the dark gives you credit for. 🕯️',
  'Wonder is just paying close, kind attention. 👁️',
  'Begin small, stay curious, and let it grow wild. 🌱',
  'A kind word now is a seed for a softer tomorrow. 🌷',
  'You can do the brave thing in a quiet, ordinary way. 🤍',
  'Let today be one shade brighter, that is plenty. 🌟',
  'The little idea is allowed to become a big one. 🎈',
  'Be patient with the magic; it likes to arrive on tiptoe. 🩰',
  'A short pause can sharpen the whole afternoon. ⏸️',
  'You are growing toward something good, even now. 🌻',
  'Let curiosity tug you somewhere a little wonderful. 🧭',
  'Tiny, kind, consistent — that is how the magic compounds. ✨',
  'You can begin again as gently as you like. 🔄',
  'A bright corner of effort lights up the whole room. 💡',
  'Be soft with the version of you that is still learning. 🫧',
  'Wonder costs nothing and changes everything it touches. 🌈',
  'Let the small win be celebrated like the big one it becomes. 🎊',
  'You are allowed to make the day a little more magical. 🦄',
  'Tend the spark today; the warmth arrives later. 🔥',
  'A curious heart turns a dull road into a discovery. 🗺️',
  'You are doing something quietly brave just by continuing. 🕊️',
  'Let the gentle idea have its turn to speak. 🤍',
  'The smallest light still changes the shape of the dark. 🕯️',
  'Be kind to your beginnings; they are doing their best. 🐣',
  'A little wonder, taken daily, keeps the dull away. 🌠',
  'You can hold the plan loosely and the joy tightly. 🎈',
  'Let curiosity be the loudest voice in the room today. 📣',
  'Your soft pace is carrying you somewhere worthwhile. 🐢',
  'A tiny experiment beats a giant assumption. 🧪',
  'You are more capable than your tired moments suggest. 💪',
  'Let the morning be a fresh, forgiving page. 📄',
  'Wonder turns an errand into a small adventure. 🧳',
  'Be patient; good things often arrive in the last draft. 📖',
  'A gentle effort, repeated, becomes a quiet triumph. 🏅',
  'You are allowed to delight in the small, specific things. 🍓',
  'Let the spark be enough proof that the fire is possible. 🔥',
  'The kindest plan is one you can actually keep. 🗒️',
  'You bring a wonder to the world that the world was missing. 🌈',
  'Be curious first; the courage tends to follow. 🧭',
  'A small act of hope outshines a big shrug of doubt. 🌟',
  'You can rest, and the dream will still be there. 🛌',
  'Let today hold one moment you would not trade. 💞',
  'Tiny magic is still magic, and it is yours. 🪄',
  'Be gentle; you are doing something hard with a soft heart. 🤍',
  'A curious question is a doorway you can always open. 🚪',
  'You are allowed to grow at the speed of joy. 🌻',
  'Let the small good thing be the headline today. 📰',
  'Wonder is the part of you that never quite grew up. 🎠',
  'Be brave in the small ways and the big ways follow. 💪',
  'A short kindness today ripples farther than you will see. 🌊',
  'You are closer to the wonderful than the worry admits. 📈',
  'Let curiosity outlast comfort, just for today. 🧭',
  'Tend the little spark; it is more powerful than it looks. 🔥',
  'You can be unfinished and still be magnificent. 🌟',
  'A gentle morning makes for a generous afternoon. ☕',
  'Let the dream stay playful; play keeps it alive. 🎈',
  'You are someone’s small daily miracle, whether you know it. 💫',
  'Be patient; wonder rewards the ones who keep looking. 👀',
  'A tiny step in the right direction is still the right direction. 👣',
  'You are allowed to begin before you feel ready. 🚀',
  'Let the soft idea grow at its own gentle pace. 🌱',
  'Wonder is the quiet superpower hiding in plain sight. ✨',
  'Be the warm light someone needed today, including you. 🕯️',
  'A small, true joy is worth more than a big, loud one. 💎',
  'You can hold both the hard and the hopeful at once. 🤲',
  'Let curiosity be the compass and joy be the map. 🗺️',
  'Tiny wonders, gathered daily, become a happy life. 🌈',
  'You are growing even when the leaves do not show it. 🌳',
  'Be gentle; even the sun rests below the horizon a while. 🌅',
  'A single brave breath can start a whole brave day. 🫁',
  'You are allowed to make today a little more yours. 🌟',
  'Let the spark be your proof that something is possible. 🔥',
  'The smallest wonder, fully felt, is a kind of magic. 🪄',
  'Be curious, be kind, and let that be enough today. 🤍',
  'A soft plan kept beats a perfect plan abandoned. 🗒️',
  'You carry a little light that the dark cannot copy. 🕯️',
  'Let wonder be the first guest you welcome each morning. 🌅',
  'You are a small, stubborn miracle in motion. 🦄',
  'Tend the tiny things, and the big things tend to follow. 🌱',
  'A daydream is just an idea trying on its costume. 🎭',
  'You are allowed to outgrow yesterday’s plan. 🌿',
  'Let the little spark of want guide the big decision. 🔥',
  'Be kind to the part of you that is trying something new. 🐣',
  'A short, honest effort beats a long, perfect intention. ⏱️',
  'You can plant joy today and pick it ripe tomorrow. 🍑',
  'Wonder is patient; it waits for you to slow down. 🐌',
  'Let the gentle answer arrive before the harsh one. 🕊️',
  'You are quietly becoming the person you keep hoping to be. 🌟',
  'A small light, kept steady, outlasts a big flare. 🕯️',
  'Be curious about the detour; it might be the destination. 🗺️',
  'You do not have to finish today to have made it count. ✅',
  'Let your softest idea be the one you protect most. 🫧',
  'A tiny step taken now beats a giant leap postponed. 👣',
  'You carry a small sun; let it warm your own day too. ☀️',
  'Be patient; the bud knows exactly when to open. 🌷',
  'A playful mind solves what a worried one only circles. 🎠',
  'You are allowed to be delighted by your own progress. 🎈',
  'Let curiosity, not perfection, write today’s first line. ✒️',
  'A small kindness boomerangs back warmer than it left. 💗',
  'You are more ready than the nervous voice insists. 💪',
  'Let wonder turn the ordinary commute into a quiet marvel. 🚋',
  'Tend the spark, trust the slow, and keep showing up. 🔥',
  'A gentle no makes room for a wholehearted yes. 🚪',
  'You are the calm and the spark; use whichever today needs. ⚡',
  'Let the small good moment be reason enough to smile. 🌼',
  'A curious heart is never truly bored, only between wonders. 🧭',
  'You are growing toward the light, even in the shade. 🌳',
  'Be brave enough to make it badly and proud enough to keep it. 🖍️',
  'Let today be small, kind, and quietly magical. 🦄',
  'A single tended spark is how every bright thing begins. ✨'
];
