// Opt-in integration. App data is created only through the real HTTP API.
// Requires a development server using a disposable local `timeline-rs` set.
import assert from 'node:assert/strict';
import { createHash, randomUUID } from 'node:crypto';
import { writeFile } from 'node:fs/promises';

const base = process.env.TIMELINE_TEST_BASE;
if (!base) throw new Error('Set TIMELINE_TEST_BASE to the isolated local test server');
if (!['127.0.0.1', 'localhost'].includes(new URL(base).hostname)) throw new Error('Timeline integration only runs on a disposable local server');
const status = await fetch(`${base}/api/v1/mongodb/status`).then(response => response.json());
assert.equal(status.host, '127.0.0.1:20337');
assert.equal(status.replicaSet, 'timeline-rs');
assert.equal(status.custom, false);
assert.equal(status.connected, true);

let cookie = '';
async function call(path: string, body?: unknown, method = body === undefined ? 'GET' : 'POST', authenticated = true) {
	const response = await fetch(`${base}${path}`, { method, headers: { ...(authenticated && cookie ? { Cookie: cookie } : {}), ...(body === undefined ? {} : { 'Content-Type': 'application/json' }) }, ...(body === undefined ? {} : { body: JSON.stringify(body) }) });
	const data = await response.json();
	return { response, data };
}
const username = `timeline-${randomUUID().slice(0, 8)}`;
const password = process.env.TIMELINE_TEST_PASSWORD || `Timeline-${randomUUID()}-9a!`;
const registered = await call('/api/v1/auth/register', { username, password, email: `${username}@example.invalid`, displayName: 'Timeline test' });
assert.equal(registered.data.ok, true, 'Fixture registration failed');
cookie = registered.response.headers.getSetCookie().map(value => value.split(';')[0]).join('; ');
const ownerId = registered.data.user.id;
assert.ok(ownerId);
const query = `ownerId=${encodeURIComponent(ownerId)}&dataPlane=home`;
const discovery = await call(`/api/v1/timeline?ownerId=${encodeURIComponent(ownerId)}`);
assert.equal(discovery.data.ok, true);
assert.equal(discovery.data.dataPlane, 'home');

const secretOldValue = `old-value-${randomUUID()}`;
const created = await call('/api/v1/things', { thingtime: ['data'], crystal: { title: 'Timeline fixture', value: secretOldValue }, visibility: 'private' });
assert.equal(created.data.ok, true, 'Fixture create failed');
const thing = created.data.thing;
assert.ok(thing?.id);
const history = () => call(`/api/v1/timeline?${query}&thingId=${encodeURIComponent(thing.id)}`);
const first = await history();
assert.equal(first.data.entries.length, 1);
assert.equal(first.data.entries[0].event.operation, 'create');
assert.equal(first.data.entries[0].event.source, 'api');

const edited = await call('/api/v1/things', { id: thing.id, crystal: { value: 'Edited remotely' }, expectedUpdatedAt: thing.updatedAt }, 'PATCH');
assert.equal(edited.data.ok, true, 'API edit failed');
const second = await history();
assert.equal(second.data.entries.length, 2);
const head = second.data.entries[0].event;
assert.equal(head.before.value.crystal.value, secretOldValue);
assert.equal(head.after.value.crystal.value, 'Edited remotely');
assert.deepEqual(head.parentIds, [first.data.entries[0].event.id]);

const raced = await Promise.all(['First edit', 'Second edit'].map(value => call('/api/v1/things', { id: thing.id, crystal: { value }, expectedUpdatedAt: edited.data.thing.updatedAt }, 'PATCH')));
assert.deepEqual(raced.map(result => result.response.status).sort(), [200, 409]);
const afterRace = await history();
assert.equal(afterRace.data.entries.length, 3, 'The refused write must not append a success event');
const latest = afterRace.data.entries[0].event;
const event = { ...latest, id: randomUUID(), operationId: randomUUID(), parentIds: [latest.id], source: 'client', mode: 'draft', clientId: 'integration-browser', label: 'Offline draft', after: { ...latest.after, value: { ...latest.after.value, crystal: { title: 'Unsaved local draft' } } } };
const pushed = await call(`/api/v1/timeline?${query}`, event);
assert.equal(pushed.data.ok, true, 'Draft push failed');
const retried = await call(`/api/v1/timeline?${query}`, event);
assert.deepEqual(retried.data, pushed.data, 'Lost-response retry must return the original event and receipt');
assert.equal((await history()).data.entries.length, 4);
assert.equal((await call(`/api/v1/things?id=${thing.id}`)).data.thing.crystal.value, latest.after.value.crystal.value, 'Uploading a draft must not overwrite live content');
assert.equal((await call(`/api/v1/timeline?${query}`, { ...event, label: 'Changed retry' })).response.status, 409);
assert.equal((await call(`/api/v1/timeline?${query}`, { ...event, id: randomUUID(), source: 'api' })).response.status, 400);
assert.equal((await call(`/api/v1/timeline?${query}&thingId=${thing.id}`, undefined, 'GET', false)).response.status, 401);
assert.equal((await call(`/api/v1/timeline?ownerId=another-account&dataPlane=home&thingId=${thing.id}`)).response.status, 409);
assert.equal((await call('/api/v1/things', { id: discovery.data.folderId }, 'DELETE')).response.status, 403);

const generic = await call(`/api/v1/things?q=${encodeURIComponent(secretOldValue)}`);
assert.equal(JSON.stringify(generic.data).includes(secretOldValue), false, 'Old private payload must not appear through ordinary search');
const version = (body: unknown) => call(`/api/v1/timeline?${query}`, body);
const restorePreview = await version({ command: 'preview-version', mode: 'restore', eventId: first.data.entries[0].event.id });
assert.equal(restorePreview.data.ok, true, 'Restore preview failed');
assert.equal(restorePreview.data.preview.result.value.crystal.value, secretOldValue);
const restoreCommand = { command: 'apply-version', mode: 'restore', eventId: first.data.entries[0].event.id, expectedHeadId: restorePreview.data.preview.expectedHeadId, operationId: randomUUID() };
assert.equal((await version({ ...restoreCommand, expectedHeadId: first.data.entries[0].event.id })).response.status, 409, 'Stale version preview must refuse');
const restored = await version(restoreCommand);
assert.equal(restored.data.ok, true, 'Restore failed');
assert.equal(restored.data.entry.event.operation, 'restore');
assert.equal((await call(`/api/v1/things?id=${thing.id}`)).data.thing.crystal.value, secretOldValue);
assert.deepEqual((await version(restoreCommand)).data, restored.data, 'A lost restore response must be idempotent');
assert.equal((await version({ ...restoreCommand, eventId: head.id })).response.status, 409, 'Changed operation payload must refuse');
const branchBase = restored.data.entry.event;
const branch = { ...event, id: randomUUID(), operationId: randomUUID(), branchId: 'alternate', parentIds: [branchBase.id], before: branchBase.after, after: { ...branchBase.after, value: { ...branchBase.after.value, crystal: { ...branchBase.after.value.crystal, value: 'Branch edit' } } } };
assert.equal((await version(branch)).data.ok, true);
assert.equal((await call('/api/v1/things', { id: thing.id, crystal: { remoteField: 'Remote edit' } }, 'PATCH')).data.ok, true);
const mergePreview = await version({ command: 'preview-version', mode: 'merge', eventId: branch.id });
assert.equal(mergePreview.data.ok, true, 'Merge preview failed');
assert.deepEqual(mergePreview.data.preview.conflicts, []);
assert.equal(mergePreview.data.preview.result.value.crystal.remoteField, 'Remote edit');
assert.equal(mergePreview.data.preview.result.value.crystal.value, 'Branch edit');
const merged = await version({ command: 'apply-version', mode: 'merge', eventId: branch.id, expectedHeadId: mergePreview.data.preview.expectedHeadId, operationId: randomUUID() });
assert.equal(merged.data.ok, true, 'Merge failed');
assert.equal(merged.data.entry.event.operation, 'merge');
assert.deepEqual(merged.data.entry.event.parentIds, [mergePreview.data.preview.expectedHeadId, branch.id]);
const divergent = { ...branch, id: randomUUID(), operationId: randomUUID(), branchId: 'conflicting', after: { ...branch.after, value: { ...branch.after.value, crystal: { ...branch.after.value.crystal, value: 'Another branch' } } } };
assert.equal((await version(divergent)).data.ok, true);
const overlap = await version({ command: 'preview-version', mode: 'merge', eventId: divergent.id });
assert.deepEqual(overlap.data.preview.conflicts.map((item: any) => item.path), [['crystal', 'value']]);
const mergeCommand = { command: 'apply-version', mode: 'merge', eventId: divergent.id, expectedHeadId: overlap.data.preview.expectedHeadId, operationId: randomUUID() };
assert.equal((await version(mergeCommand)).response.status, 409);
assert.equal((await version({ ...mergeCommand, choices: { '["crystal","value"]': 'incoming' } })).data.ok, true);
assert.equal((await call(`/api/v1/things?id=${thing.id}`)).data.thing.crystal.value, 'Another branch');
// Named branches keep a separate current-version record for every Thing.
const branchId = `branch-${randomUUID()}`;
const branchCommand = { command: 'create-branch', operationId: randomUUID(), branchId, thingId: thing.id, eventId: branchBase.id, expectedRevision: 0, name: 'Design experiment' };
const named = await version(branchCommand);
assert.equal(named.data.ok, true, 'Named branch creation failed');
assert.equal(named.data.head.revision, 1);
assert.equal(named.data.branch.name, branchCommand.name);
assert.deepEqual((await version(branchCommand)).data, named.data, 'Branch creation retry must return the original receipt');
assert.equal((await version({ ...branchCommand, name: 'Changed retry' })).response.status, 409);
const branchPage = () => call(`/api/v1/timeline?${query}&branches=1&thingId=${thing.id}`);
assert.equal((await branchPage()).data.branches[0].head.eventId, branchBase.id);
const exact = await call(`/api/v1/timeline?${query}&eventId=${branchBase.id}&thingId=${thing.id}`);
assert.equal(exact.response.status, 200); assert.deepEqual(exact.data.entry.event, branchBase);
assert.equal(exact.response.headers.get('cache-control'), 'private, no-store');
assert.equal((await call(`/api/v1/timeline?${query}&eventId=${branchBase.id}&thingId=wrong-thing`)).response.status, 404);
assert.equal((await call(`/api/v1/timeline?${query}&eventId=${branchBase.id}`, undefined, 'GET', false)).response.status, 401);
const branchThingId = `timeline-branch-${createHash('sha256').update(JSON.stringify([ownerId, branchId])).digest('hex')}`;
assert.equal((await call(`/api/v1/things?id=${branchThingId}`)).response.status, 404, 'Generic reads must not expose branch envelopes, even to the owner');
assert.equal((await call('/api/v1/things', { id: branchThingId, crystal: { name: 'Forged branch' } }, 'PATCH')).response.status, 403);
assert.equal((await call('/api/v1/things', { thingtime: ['timeline-branch'], crystal: { name: 'Forged branch' } })).response.status, 403);
const currentVersion = (await history()).data.entries.find((item: any) => item.event.mode === 'revision').event;
const pushes = [currentVersion.id, branch.id].map(eventId => ({ command: 'advance-branch', operationId: randomUUID(), branchId, thingId: thing.id, eventId, expectedRevision: 1, name: null }));
const branchRace = await Promise.all(pushes.map(version));
assert.deepEqual(branchRace.map(result => result.response.status).sort(), [200, 409], 'Concurrent branch pushes must have one winner');
const winner = branchRace.findIndex(result => result.response.status === 200);
assert.deepEqual((await version(pushes[winner])).data, branchRace[winner].data, 'A push retry must not advance the revision again');
assert.equal((await branchPage()).data.branches[0].head.revision, 2);
assert.equal((await version({ ...pushes[winner], operationId: randomUUID(), expectedRevision: 2, eventId: branchBase.id })).response.status, 409, 'A push cannot silently rewind or erase branch ancestry');
assert.equal((await call(`/api/v1/things?id=${thing.id}`)).data.thing.crystal.value, 'Another branch', 'Branch moves must not change published content');
const anotherThing = await call('/api/v1/things', { thingtime: ['data'], crystal: { title: 'Another branch member' }, visibility: 'private' });
assert.equal(anotherThing.data.ok, true);
const memberHistory = await call(`/api/v1/timeline?${query}&thingId=${anotherThing.data.thing.id}`);
const attached = await version({ command: 'advance-branch', operationId: randomUUID(), branchId, thingId: anotherThing.data.thing.id, eventId: memberHistory.data.entries[0].event.id, expectedRevision: 0, name: null });
assert.equal(attached.data.ok, true, 'Adding a second Thing to one branch failed');
assert.equal(attached.data.branch.id, branchId);
assert.notEqual(attached.data.head.id, named.data.head.id);
assert.equal((await branchPage()).data.branches[0].head.revision, 2, 'Another Thing membership must not rewrite the earlier head');
const otherBranch = await version({ ...branchCommand, branchId: `branch-${randomUUID()}`, operationId: randomUUID(), name: 'Alternate design' });
assert.equal(otherBranch.data.ok, true);
const branchFirst = await call(`/api/v1/timeline?${query}&branches=1&thingId=${thing.id}&limit=1`);
assert.equal(branchFirst.data.branches.length, 1); assert.ok(branchFirst.data.nextBefore);
const branchOlder = await call(`/api/v1/timeline?${query}&branches=1&thingId=${thing.id}&limit=1&before=${branchFirst.data.nextBefore}`);
assert.equal(branchOlder.data.branches[0].branch.id, branchId); assert.equal(branchOlder.data.nextBefore, null);
assert.equal((await call(`/api/v1/things?q=${encodeURIComponent('Design experiment')}`)).data.things?.some((item: any) => item.crystal?.name === 'Design experiment') ?? false, false, 'Branch metadata stays private to Timeline');
const invalidDefinition = { ...event, id: randomUUID(), operationId: randomUUID(), parentIds: [currentVersion.id], after: { adapter: 'definition-source', version: 1, value: { source: '{unfinished' } } };
assert.equal((await version(invalidDefinition)).data.ok, true, 'Incomplete draft text must remain recoverable');
assert.equal((await version({ command: 'preview-version', mode: 'restore', eventId: invalidDefinition.id })).response.status, 422, 'An incomplete definition needs an actionable refusal, not an internal server error');
assert.equal((await version({ command: 'preview-version', mode: 'merge', eventId: branch.id, choices: { '["already-resolved"]': 'incoming' } })).response.status, 422);
const disposable = await call('/api/v1/things', { thingtime: ['data'], crystal: { title: 'Delete history fixture', value: 'Retained in history' }, visibility: 'private' });
assert.equal(disposable.data.ok, true);
assert.equal((await call('/api/v1/things', { id: disposable.data.thing.id }, 'DELETE')).data.ok, true);
const deletedHistory = await call(`/api/v1/timeline?${query}&thingId=${disposable.data.thing.id}`);
assert.equal(deletedHistory.data.entries[0].event.operation, 'delete');
assert.equal(deletedHistory.data.entries[0].event.before.value.crystal.value, 'Retained in history');
assert.equal(deletedHistory.data.entries[0].event.after, null);
assert.deepEqual(deletedHistory.data.entries[0].event.parentIds, [deletedHistory.data.entries[1].event.id]);
assert.equal((await call(`/api/v1/things?id=${disposable.data.thing.id}`)).response.status, 404);
const originalCookie = cookie;
const outsiderName = `timeline-${randomUUID().slice(0, 8)}`;
const outsider = await call('/api/v1/auth/register', { username: outsiderName, password, email: `${outsiderName}@example.invalid`, displayName: 'Timeline privacy fixture' });
assert.equal(outsider.data.ok, true);
cookie = outsider.response.headers.getSetCookie().map(value => value.split(';')[0]).join('; ');
const outsiderQuery = `ownerId=${encodeURIComponent(outsider.data.user.id)}&dataPlane=home`;
assert.equal((await call(`/api/v1/timeline?${outsiderQuery}&eventId=${branchBase.id}`)).response.status, 404);
assert.deepEqual((await call(`/api/v1/timeline?${outsiderQuery}&branches=1&thingId=${thing.id}`)).data.branches, []);
assert.equal((await call(`/api/v1/timeline?${outsiderQuery}`, { ...branchCommand, operationId: randomUUID(), branchId: `branch-${randomUUID()}` })).response.status, 404);
cookie = originalCookie;
await writeFile('/tmp/thingtime-timeline-fixture.json', JSON.stringify({ base, username, password, cookie, ownerId, thingId: thing.id, folderId: discovery.data.folderId }), { mode: 0o600 });
console.log(JSON.stringify({ ok: true, checks: ['disposable-replica-set', 'api-create-update-delete-history', 'stale-write-rollback', 'durable-draft-sync', 'idempotent-retry', 'provenance-refusal', 'account-isolation', 'protected-folder', 'private-search', 'restore-and-exact-retry', 'three-way-merge', 'explicit-conflict-resolution', 'named-branches', 'branch-push-CAS-and-retry', 'branch-fast-forward-only', 'relational-branch-memberships', 'branch-pagination', 'private-exact-version', 'protected-branch-CRUD', 'foreign-branch-refusal'], fixture: '/tmp/thingtime-timeline-fixture.json' }));
